<?php
declare(strict_types=1);
namespace Vigilancia\Services;

use PDO;
use Throwable;
use Vigilancia\Exceptions\HttpException;
use Vigilancia\Repositories\EventRepository;
use Vigilancia\Repositories\OperationalRepository;
use Vigilancia\Repositories\PermissionRepository;
use Vigilancia\Repositories\SecurityLogRepository;
use Vigilancia\Support\ClientInfo;

final class EventService
{
    private AuthorizationService $authorization;
    private const PRIORITIES=['normal'=>1,'important'=>2,'critical'=>3];
    public function __construct(private PDO$pdo,private EventRepository$repo,private OperationalRepository$operations,private EventEvidenceService$assets,private SecurityLogRepository$logs){$this->authorization=new AuthorizationService(new PermissionRepository($pdo));}

    public function types(array$actor,bool$all=false):array{$this->requireAny($actor,['events.manage','events.review','events.create']);$items=$this->repo->types(!$all||!in_array('events.manage',$this->authorization->permissionsFor($actor),true));return array_values(array_filter($items,static fn(array$type):bool=>($type['event_scope']??'incident')==='incident'));}
    public function saveType(array$actor,array$in):array{$this->authorization->require($actor,'events.manage');$name=trim((string)($in['name']??''));$code=strtolower(trim((string)($in['code']??'')));$priority=(string)($in['default_priority']??'normal');$id=(int)($in['id']??0);if(mb_strlen($name)<3||mb_strlen($name)>120||(!$id&&!preg_match('/^[a-z][a-z0-9_]{2,59}$/',$code))||($id&&$code!==''&&!preg_match('/^[a-z][a-z0-9_]{2,59}$/',$code))||!isset(self::PRIORITIES[$priority]))throw new HttpException('Los datos del tipo de evento no son válidos.',422);$id=$this->repo->saveType(['id'=>$id,'code'=>$code,'name'=>$name,'order'=>max(1,min(999,(int)($in['sort_order']??100))),'priority'=>$priority,'required'=>!empty($in['evidence_required'])?1:0,'active'=>array_key_exists('is_active',$in)?(!empty($in['is_active'])?1:0):1]);$this->audit($actor,'events.type_saved',['event_type_id'=>$id]);return['id'=>$id];}
    public function events(array$actor):array{$this->requireAny($actor,['events.manage','events.review','events.create']);return$this->repo->listEvents($actor);}
    public function details(array$actor,int$id):array{$this->requireAny($actor,['events.manage','events.review','events.create']);$event=$this->scopedEvent($actor,$id);return['event'=>$event,'comments'=>$this->repo->comments($id),'evidence'=>$this->repo->evidenceForEvent($id)];}
    public function createGuardEvent(array$in):array{$session=$this->guardSession();$type=$this->activeType((int)($in['event_type_id']??0));if(($type['event_scope']??'incident')!=='incident')throw new HttpException('El tipo seleccionado no corresponde a una incidencia.',422);$title=$this->longText((string)($in['title']??''),'El título',5,180);$description=$this->description($in);$priority=$this->priority((string)($in['priority']??$type['default_priority']),(string)$type['default_priority']);$evidence=is_array($in['evidence']??null)?$in['evidence']:[];if((bool)$type['evidence_required']&&!$evidence)throw new HttpException('Este tipo de incidencia requiere al menos una evidencia.',422);if(count($evidence)>10)throw new HttpException('Solo se permiten hasta 10 evidencias por incidencia.',422);
        $this->pdo->beginTransaction();try{$id=$this->repo->createEvent($this->eventData($session,(int)$type['id'],$title,$description,$priority));foreach($evidence as$item)$this->saveEvidence($session,$id,is_array($item)?$item:[]);$this->pdo->commit();}catch(Throwable$e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw$e;}$this->guardAudit($session,'incidents.created',['event_id'=>$id,'title'=>$title,'evidence_count'=>count($evidence)]);return['id'=>$id];}
    public function addEvidence(array$in):array{$session=$this->guardSession();$event=$this->repo->event((int)($in['event_id']??0));if(!$event||(int)$event['operational_session_id']!==(int)$session['id']||(int)$event['guard_user_id']!==(int)$session['guard_user_id']||$event['status']!=='submitted')throw new HttpException('La incidencia no existe o no pertenece a la sesión activa.',404);$id=$this->saveEvidence($session,(int)$event['id'],$in);$this->guardAudit($session,'incidents.evidence_added',['event_id'=>$event['id'],'evidence_id'=>$id]);return['id'=>$id];}
    public function comment(array$actor,array$in):array{$this->authorization->require($actor,'events.review');$event=$this->scopedEvent($actor,(int)($in['event_id']??0));$comment=$this->longText((string)($in['comment']??''),'El comentario',10,1000);$this->repo->addComment((int)$event['id'],(int)$actor['id'],$comment);$this->audit($actor,'events.commented',['event_id'=>$event['id']]);return[];}
    public function cancel(array$actor,array$in):array{$this->requireAny($actor,['events.manage','events.review']);$event=$this->scopedEvent($actor,(int)($in['event_id']??0));if($event['status']==='cancelled')throw new HttpException('El evento ya está cancelado.',409);$reason=$this->longText((string)($in['reason']??''),'El motivo',10,500);$this->repo->cancel((int)$event['id'],(int)$actor['id'],$reason);$this->audit($actor,'events.cancelled',['event_id'=>$event['id'],'reason'=>$reason]);return[];}

    public function guardDashboard():array{$session=$this->guardSession();$open=$this->repo->openRound((int)$session['guard_user_id']);$events=$this->repo->listEvents(['role_code'=>'guard','id'=>$session['guard_user_id']]);foreach($events as&$event){$comments=$this->repo->comments((int)$event['id']);$event['latest_comment']=$comments?end($comments)['comment']:null;}unset($event);$novelties=$this->repo->previousNovelties((int)$session['location_id'],(int)$session['access_point_id'],(int)$session['id']);foreach($novelties as&$novelty){$comments=$this->repo->comments((int)$novelty['event_id']);$novelty['latest_comment']=$comments?end($comments)['comment']:null;}unset($novelty);return['scope'=>['guard_name'=>$session['guard_name'],'client_name'=>$session['client_name'],'location_name'=>$session['location_name'],'point_name'=>$session['access_point_name']],'types'=>array_values(array_filter($this->repo->types(),fn($t)=>!in_array($t['code'],['round','shift_novelty'],true))),'events'=>$events,'open_round'=>$open,'round_policy'=>$this->repo->policy((int)$session['location_id']),'previous_novelties'=>$novelties,'novelty'=>$this->repo->noveltyForSession((int)$session['id'])];}
    public function startRound(array$in):array{$session=$this->guardSession();if($this->repo->openRound((int)$session['guard_user_id']))throw new HttpException('Ya tienes un recorrido abierto.',409);$type=$this->typeByCode('round');$kind=(string)($in['round_kind']??'free');if(!in_array($kind,['scheduled','free'],true))throw new HttpException('El tipo de recorrido no es válido.',422);$title=$kind==='scheduled'?'Recorrido programado':'Recorrido adicional';$description=trim((string)($in['description']??''))?:($kind==='scheduled'?'Recorrido programado del turno':'Recorrido adicional libre');$event=$this->repo->createEvent($this->eventData($session,(int)$type['id'],$title,$description,'normal'));$id=$this->repo->createRound(['event_id'=>$event,'session_id'=>$session['id'],'client_id'=>$session['client_id'],'location_id'=>$session['location_id'],'point_id'=>$session['access_point_id'],'guard_id'=>$session['guard_user_id'],'kind'=>$kind]);$this->guardAudit($session,'rounds.started',['round_id'=>$id]);return['id'=>$id,'event_id'=>$event];}
    public function finishRound(array$in):array{$session=$this->guardSession();$round=$this->repo->round((int)($in['round_id']??0));if(!$round||(int)$round['guard_user_id']!==(int)$session['guard_user_id']||(int)$round['operational_session_id']!==(int)$session['id']||$round['status']!=='open')throw new HttpException('No existe un recorrido abierto de esta sesión.',404);if((int)$round['evidence_count']<1)throw new HttpException('Agrega al menos una evidencia antes de finalizar.',422);$observations=$this->longText((string)($in['observations']??''),'Las observaciones',10,2000);$this->repo->finishRound((int)$round['id'],$observations);$this->guardAudit($session,'rounds.completed',['round_id'=>$round['id']]);return[];}
    public function rounds(array$actor):array{$this->requireAny($actor,['rounds.view','rounds.review']);return$this->repo->listRounds($actor);}
    public function supervisorCloseRound(array$actor,array$in):array{$this->authorization->require($actor,'rounds.review');$round=$this->repo->round((int)($in['round_id']??0));if(!$round)throw new HttpException('El recorrido no existe.',404);$event=$this->scopedEvent($actor,(int)$round['event_id']);$comment=$this->longText((string)($in['comment']??''),'El comentario',10,500);$this->repo->supervisorCloseRound((int)$round['id'],(int)$actor['id'],$comment);$this->audit($actor,'rounds.supervisor_closed',['round_id'=>$round['id'],'event_id'=>$event['id']]);return[];}
    public function createNovelty(array$in):array{$session=$this->guardSession();if($this->repo->noveltyForSession((int)$session['id']))throw new HttpException('La novedad de este turno ya fue registrada.',409);$without=!empty($in['without_news']);$description=$without?'Turno entregado sin novedades':$this->longText((string)($in['description']??''),'La novedad',10,2000);$type=$this->typeByCode('shift_novelty');$event=$this->repo->createEvent($this->eventData($session,(int)$type['id'],'Novedad de entrega de turno',$description,'normal'));$id=$this->repo->createNovelty(['session_id'=>$session['id'],'event_id'=>$event,'guard_id'=>$session['guard_user_id'],'client_id'=>$session['client_id'],'location_id'=>$session['location_id'],'point_id'=>$session['access_point_id'],'status'=>$without?'no_news':'reported','description'=>$description]);$this->guardAudit($session,'shifts.novelty_created',['novelty_id'=>$id,'event_id'=>$event]);return['id'=>$id,'event_id'=>$event];}

    private function saveEvidence(array$session,int$eventId,array$item):int{$totals=$this->repo->evidenceTotals($eventId);if((int)$totals['files']>=10)throw new HttpException('El evento ya tiene el máximo de 10 evidencias.',409);$event=$this->repo->event($eventId);$stamp=gmdate('Y-m-d H:i:s').' UTC · '.$session['guard_name'].' · '.$session['client_name'].' · '.$session['location_name'];$file=$this->assets->save((string)($item['data']??$item['evidence_data']??''),$stamp,isset($item['duration_seconds'])?(float)$item['duration_seconds']:null);if((int)$totals['bytes']+$file['size']>20*1024*1024)throw new HttpException('El conjunto de evidencias supera 20 MB.',422);return$this->repo->addEvidence(['event_id'=>$eventId,'user_id'=>$session['guard_user_id'],'media_type'=>$file['media_type'],'mime'=>$file['mime'],'path'=>$file['path'],'size'=>$file['size'],'duration'=>$file['duration'],'watermark'=>$stamp]);}
    private function guardSession():array{$id=(int)($_SESSION['operational_session_id']??0);$guard=(int)($_SESSION['operational_guard_id']??0);$row=$id?$this->operations->session($id):null;if(!$row||$row['status']!=='active'||(int)$row['guard_user_id']!==$guard)throw new HttpException('Se requiere una sesión operativa activa.',401);return$row;}
    private function eventData(array$s,int$type,string$title,string$description,string$priority):array{return['type_id'=>$type,'session_id'=>(int)$s['id'],'client_id'=>(int)$s['client_id'],'location_id'=>(int)$s['location_id'],'point_id'=>(int)$s['access_point_id'],'guard_id'=>(int)$s['guard_user_id'],'title'=>$title,'description'=>$description,'priority'=>$priority,'created_by'=>(int)$s['guard_user_id']];}
    private function activeType(int$id):array{$t=$this->repo->type($id);if(!$t||!(bool)$t['is_active'])throw new HttpException('El tipo de evento no está disponible.',422);return$t;}private function typeByCode(string$code):array{foreach($this->repo->types()as$t)if($t['code']===$code)return$t;throw new HttpException('No está configurado el tipo de evento requerido.',500);}
    private function description(array$in):string{return$this->longText((string)($in['description']??''),'La descripción',10,2000);}private function priority(string$value,string$default):string{if(!isset(self::PRIORITIES[$value]))throw new HttpException('La prioridad no es válida.',422);return self::PRIORITIES[$value]<self::PRIORITIES[$default]?$default:$value;}
    private function longText(string$v,string$label,int$min,int$max):string{$v=trim($v);$n=mb_strlen($v);if($n<$min||$n>$max)throw new HttpException("$label debe contener entre $min y $max caracteres.",422);return$v;}
    private function scopedEvent(array$a,int$id):array{$e=$this->repo->event($id);if(!$e||!$this->repo->inScope($a,$e))throw new HttpException('El evento no existe o está fuera de tu alcance.',404);return$e;}private function requireAny(array$a,array$p):void{if(array_intersect($p,$this->authorization->permissionsFor($a))===[])throw new HttpException('No cuentas con permiso para consultar este módulo.',403);}
    private function audit(array$a,string$event,array$c):void{$this->logs->record((int)$a['id'],$event,ClientInfo::ip(),ClientInfo::userAgent(),$c);}private function guardAudit(array$s,string$event,array$c):void{$this->logs->record((int)$s['guard_user_id'],$event,ClientInfo::ip(),ClientInfo::userAgent(),$c);}
}
