<?php
declare(strict_types=1);
namespace Vigilancia\Services;
use DateTimeImmutable;use DateTimeZone;use PDO;use Vigilancia\Exceptions\HttpException;use Vigilancia\Operations\AttendanceClassifier;use Vigilancia\Repositories\OfflineRepository;use Vigilancia\Repositories\OperationalRepository;use Vigilancia\Repositories\PermissionRepository;use Vigilancia\Repositories\SecurityLogRepository;use Vigilancia\Support\ClientInfo;
final class OfflineService
{
 private AuthorizationService $authorization;private const TYPES=['entry','exit','round_start','round_end','event','evidence','comment'];
 public function __construct(private PDO$pdo,private OfflineRepository$repo,private OfflineEvidenceService$evidence,private SecurityLogRepository$logs,private OperationalRepository$operations){$this->authorization=new AuthorizationService(new PermissionRepository($pdo));}
 public function sync(string$token,array$input):array{$device=$token===''?null:$this->repo->deviceByToken(hash('sha256',$token));if(!$device)throw new HttpException('El dispositivo offline no está autorizado o su autorización expiró.',401);$ops=$input['operations']??null;if(!is_array($ops)||count($ops)>50)throw new HttpException('El lote offline debe contener entre 0 y 50 operaciones.',422);$results=[];foreach($ops as$op)$results[]=$this->receive($device,is_array($op)?$op:[]);$this->repo->touchDevice((int)$device['id']);$this->logs->record((int)$device['guard_user_id'],'offline.batch_synced',ClientInfo::ip(),ClientInfo::userAgent(),['count'=>count($results)]);return['results'=>$results,'server_time'=>gmdate(DATE_ATOM)];}
 public function conflicts(array$actor):array{$this->authorization->require($actor,'offline_conflicts.manage');return$this->repo->reviewable($actor);}
 public function review(array$actor,array$input):array{$this->authorization->require($actor,'offline_conflicts.manage');$id=(int)($input['operation_id']??0);$decision=(string)($input['decision']??'');$comment=trim((string)($input['comment']??''));if(!in_array($decision,['accepted','rejected'],true))throw new HttpException('La decisión no es válida.',422);if(mb_strlen($comment)<10||mb_strlen($comment)>500)throw new HttpException('El comentario debe contener entre 10 y 500 caracteres.',422);$row=$this->repo->scopedReviewable($id,$actor);if(!$row)throw new HttpException('La operación offline no existe o está fuera de tu alcance.',404);$this->pdo->beginTransaction();try{$this->repo->review($id,$decision,(int)$actor['id'],$comment);if($decision==='accepted'&&$row['operation_type']==='exit')$this->applyReviewedExit($row);$this->pdo->commit();}catch(\Throwable$e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw$e;}$this->logs->record((int)$actor['id'],'offline.operation_reviewed',ClientInfo::ip(),ClientInfo::userAgent(),['operation_id'=>$id,'decision'=>$decision]);return[];}
 private function receive(array$device,array$op):array{$uuid=strtolower(trim((string)($op['uuid']??'')));if(!preg_match('/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/',$uuid))throw new HttpException('Una operación contiene un UUID inválido.',422);$existing=$this->repo->existing($uuid);if($existing)return['uuid'=>$uuid,'status'=>$existing['status'],'duplicate'=>true];$type=(string)($op['type']??'');if(!in_array($type,self::TYPES,true))throw new HttpException('El tipo de operación offline no está permitido.',422);$payload=is_array($op['payload']??null)?$op['payload']:[];$occurred=$this->utc((string)($op['occurred_at']??''));$age=time()-$occurred->getTimestamp();if($age < -300)throw new HttpException('La fecha de una operación offline está en el futuro.',422);$status=$age>43200?'expired':'synchronized';$key=substr(trim((string)($op['entity_key']??'')),0,120);$group=null;$conflict=$key!==''?$this->repo->conflict($key):null;if($conflict&&$conflict['client_uuid']!==$uuid){$status='conflict';$group=$conflict['conflict_group']?:$this->uuid();$this->repo->markConflict((int)$conflict['id'],$group);}$evidence=$this->evidence->save(isset($op['evidence_data'])?(string)$op['evidence_data']:null);$data=['uuid'=>$uuid,'device_id'=>(int)$device['id'],'guard_id'=>(int)$device['guard_user_id'],'session_id'=>(int)($payload['operational_session_id']??0),'client_id'=>(int)($payload['client_id']??0),'location_id'=>(int)($payload['location_id']??0),'point_id'=>(int)($payload['access_point_id']??0),'type'=>$type,'entity_key'=>$key,'payload'=>$payload,'evidence'=>$evidence,'occurred_at'=>$occurred->format('Y-m-d H:i:s'),'status'=>$status,'conflict_group'=>$group];$this->repo->insert($data);if($status==='synchronized'&&$type==='exit')$this->applyOfflineExit($device,$data,$occurred);return['uuid'=>$uuid,'status'=>$status,'delete_local_evidence'=>$status==='synchronized'];}
 private function applyOfflineExit(array$device,array$data,DateTimeImmutable$occurred):void{$this->closeSessionIfActive((int)$data['session_id'],(int)$device['guard_user_id'],$occurred);}
 private function applyReviewedExit(array$row):void{$this->closeSessionIfActive((int)$row['operational_session_id'],(int)$row['guard_user_id'],new DateTimeImmutable($row['occurred_at'],new DateTimeZone('UTC')));}
 private function closeSessionIfActive(int$sessionId,int$guardId,DateTimeImmutable$occurred):void{$session=$sessionId?$this->operations->session($sessionId):null;if(!$session||$session['status']!=='active'||(int)$session['guard_user_id']!==$guardId)return;$end=new DateTimeImmutable($session['scheduled_end_at'],new DateTimeZone('UTC'));$result=AttendanceClassifier::exit($occurred,$end,(int)$session['early_departure_tolerance_minutes'],(int)$session['overtime_after_minutes']);$this->operations->close((int)$session['id'],$occurred->format('Y-m-d H:i:s'),$result['classification'],$result['minutes_early'],$result['overtime_minutes'],'offline',$guardId,null);}
 private function utc(string$value):DateTimeImmutable{try{return(new DateTimeImmutable($value))->setTimezone(new DateTimeZone('UTC'));}catch(\Throwable){throw new HttpException('La fecha offline no es válida.',422);}}private function uuid():string{$h=bin2hex(random_bytes(16));return substr($h,0,8).'-'.substr($h,8,4).'-4'.substr($h,13,3).'-a'.substr($h,17,3).'-'.substr($h,20);}
}
