<?php
declare(strict_types=1);
namespace Vigilancia\Services;
use Vigilancia\Exceptions\HttpException;use Vigilancia\Repositories\PermissionRepository;use Vigilancia\Repositories\ReportRepository;use Vigilancia\Repositories\SecurityLogRepository;use Vigilancia\Support\ClientInfo;
final class ReportService
{
 private AuthorizationService$auth;public const TYPES=['attendance'=>'Asistencia','late'=>'Retardos','absences'=>'Faltas','worked_hours'=>'Horas trabajadas','incidents'=>'Incidencias','events'=>'Eventos','rounds'=>'Recorridos','visits'=>'Visitas','guard_activity'=>'Actividad por vigilante','location_activity'=>'Actividad por lugar','supervisions'=>'Supervisiones'];
 public function __construct(private ReportRepository$repo,PermissionRepository$permissions,private SecurityLogRepository$logs){$this->auth=new AuthorizationService($permissions);}
 public function catalog(array$a):array{$this->authorize($a);$types=self::TYPES;if($a['role_code']==='resident')$types=['visits'=>self::TYPES['visits']];return['types'=>$types,'filters'=>$this->repo->catalog($a),'items'=>$this->repo->reports($a),'max_range_days'=>90];}
 public function create(array$a,array$in):array{$this->authorize($a);$type=(string)($in['report_type']??'');if(!isset(self::TYPES[$type])||($a['role_code']==='resident'&&$type!=='visits'))throw new HttpException('El tipo de reporte no está autorizado.',422);$from=(string)($in['date_from']??'');$to=(string)($in['date_to']??'');$start=\DateTimeImmutable::createFromFormat('!Y-m-d',$from);$end=\DateTimeImmutable::createFromFormat('!Y-m-d',$to);if(!$start||!$end||$end<$start||$start->diff($end)->days>90)throw new HttpException('El rango debe ser válido y no superar 90 días.',422);$filters=['date_from'=>$from,'date_to'=>$to,'client_id'=>(int)($in['client_id']??0),'location_id'=>(int)($in['location_id']??0),'access_point_id'=>(int)($in['access_point_id']??0),'guard_id'=>(int)($in['guard_id']??0),'shift_id'=>(int)($in['shift_id']??0)];$folio='REP-'.gmdate('Ymd-His').'-'.strtoupper(bin2hex(random_bytes(2)));$id=$this->repo->create($folio,$type,$filters,(int)$a['id']);$this->logs->record((int)$a['id'],'reports.generated',ClientInfo::ip(),ClientInfo::userAgent(),['record_type'=>'report','record_id'=>$id,'folio'=>$folio,'report_type'=>$type,'filters'=>$filters]);return['id'=>$id,'folio'=>$folio,'url'=>'report.php?id='.$id];}
 public function report(array$a,int$id):array{$this->authorize($a);$report=$this->repo->report($a,$id);if(!$report)throw new HttpException('El reporte no existe o está fuera de tu alcance.',404);$filters=json_decode((string)$report['filters_json'],true,512,JSON_THROW_ON_ERROR);$rows=$this->repo->data($a,(string)$report['report_type'],$filters);return['report'=>$report,'title'=>self::TYPES[$report['report_type']]??$report['report_type'],'filters'=>$filters,'rows'=>$rows,'evidence'=>in_array($report['report_type'],['events','incidents'],true)?$this->repo->evidenceForEvents(array_map('intval',array_column($rows,'id'))):[]];}
 private function authorize(array$a):void{if($a['role_code']==='resident')$this->auth->require($a,'reports.own_history');else$this->auth->require($a,'reports.view');}
}
