<?php
declare(strict_types=1);
namespace Vigilancia\Services;
use PDO;use Throwable;use Vigilancia\Exceptions\HttpException;use Vigilancia\Repositories\PermissionRepository;use Vigilancia\Repositories\SecurityLogRepository;use Vigilancia\Repositories\SupervisionRepository;use Vigilancia\Support\ClientInfo;

final class SupervisionService
{
 private AuthorizationService$auth;
 public function __construct(private PDO$pdo,private SupervisionRepository$repo,private SupervisionEvidenceService$assets,private SecurityLogRepository$logs){$this->auth=new AuthorizationService(new PermissionRepository($pdo));}
 public function catalog(array$a):array{$this->auth->require($a,'supervisions.manage');$locations=$this->repo->locations($a);return['actor_name'=>$a['full_name'],'confirmation_pin_configured'=>(bool)$this->repo->actorPin((int)$a['id']),'locations'=>$locations,'points'=>$this->repo->points(array_map('intval',array_column($locations,'id'))),'schedules'=>$this->repo->schedules($a)];}
 public function lists(array$a):array{$this->auth->require($a,'supervisions.manage');return$this->repo->lists($a);}
 public function schedule(array$a,array$in):array{$this->auth->require($a,'supervisions.schedule');$location=(int)($in['location_id']??0);$scope=$this->location($a,$location);$points=$this->points($location,$in['access_point_ids']??[]);$frequency=(string)($in['frequency']??'manual');if(!in_array($frequency,['manual','per_shift','daily','weekly','monthly'],true))throw new HttpException('La frecuencia no es válida.',422);$date=trim((string)($in['scheduled_at']??''));$timestamp=strtotime($date);if(!$timestamp)throw new HttpException('La fecha programada no es válida.',422);$id=$this->repo->createSchedule(['client_id'=>$scope['client_id'],'location_id'=>$location,'frequency'=>$frequency,'scheduled_at'=>gmdate('Y-m-d H:i:s',$timestamp),'user_id'=>$a['id']],$points);$this->audit($a,'supervisions.scheduled',['schedule_id'=>$id,'location_id'=>$location,'points'=>$points]);return['id'=>$id];}
 public function start(array$a,array$in):array{$this->auth->require($a,'supervisions.manage');$schedule=(int)($in['schedule_id']??0);if($schedule){$row=$this->repo->schedule($schedule);if(!$row||$row['status']!=='pending')throw new HttpException('La supervisión programada no está disponible.',409);$scope=$this->location($a,(int)$row['location_id']);$points=$this->repo->schedulePoints($schedule);}else{$location=(int)($in['location_id']??0);$scope=$this->location($a,$location);$points=$this->points($location,$in['access_point_ids']??[]);}$folio='SUP-'.gmdate('Ymd').'-'.strtoupper(bin2hex(random_bytes(3)));$id=$this->repo->create(['folio'=>$folio,'schedule_id'=>$schedule,'client_id'=>$scope['client_id'],'location_id'=>$scope['id'],'supervisor_id'=>$a['id']],$points);$this->audit($a,'supervisions.started',['supervision_id'=>$id,'folio'=>$folio]);return['id'=>$id,'folio'=>$folio];}
 public function detail(array$a,int$id):array{$this->auth->require($a,'supervisions.manage');$s=$this->scoped($a,$id);return$this->repo->detail((int)$s['id']);}
 public function evidence(array$a,array$in):array{$this->auth->require($a,'supervisions.manage');$s=$this->scoped($a,(int)($in['supervision_id']??0));if($s['status']!=='in_progress')throw new HttpException('Una supervisión finalizada ya no admite evidencias.',409);$watermark=gmdate('Y-m-d H:i:s').' UTC · '.$a['full_name'].' · '.$s['client_name'].' · '.$s['location_name'];$file=$this->assets->save((string)($in['evidence_data']??''),$watermark);$id=$this->repo->addEvidence(['supervision_id'=>$s['id'],'user_id'=>$a['id'],'mime'=>$file['mime'],'path'=>$file['path'],'size'=>$file['size'],'watermark'=>$watermark]);$this->audit($a,'supervisions.evidence_added',['supervision_id'=>$s['id'],'evidence_id'=>$id]);return['id'=>$id];}
 public function finish(array$a,array$in):array{$this->auth->require($a,'supervisions.manage');$s=$this->scoped($a,(int)($in['supervision_id']??0));if($s['status']!=='in_progress')throw new HttpException('La supervisión ya fue finalizada.',409);$observations=$this->text((string)($in['observations']??''),'Las observaciones',10,3000);$supervisorName=trim((string)($in['supervisor_name']??''));$supervisorPin=(string)($in['supervisor_pin']??'');if(mb_strtolower($supervisorName)!==mb_strtolower(trim((string)$a['full_name']))||!preg_match('/^\d{6}$/',$supervisorPin)||!($hash=$this->repo->actorPin((int)$a['id']))||!password_verify($supervisorPin,$hash))throw new HttpException('La confirmación del supervisor no es válida.',422);$absent=!empty($in['responsible_absent']);$responsibleId=null;$responsibleName=null;$reason=null;if($absent){$reason=$this->text((string)($in['absence_reason']??''),'El motivo de ausencia',10,500);}else{$responsibleName=trim((string)($in['responsible_name']??''));$pin=(string)($in['responsible_pin']??'');$responsible=$this->repo->responsibleByName((int)$s['location_id'],$responsibleName);if(!$responsible||!preg_match('/^\d{6}$/',$pin)||!$responsible['pin_hash']||!password_verify($pin,$responsible['pin_hash']))throw new HttpException('La confirmación del vigilante o responsable no es válida.',422);$responsibleId=(int)$responsible['id'];$responsibleName=$responsible['full_name'];}$this->repo->finish((int)$s['id'],['observations'=>$observations,'supervisor_name'=>$a['full_name'],'responsible_id'=>$responsibleId,'responsible_name'=>$responsibleName,'absent'=>$absent?1:0,'absence_reason'=>$reason]);$this->audit($a,'supervisions.completed',['supervision_id'=>$s['id'],'folio'=>$s['folio'],'responsible_absent'=>$absent]);return['folio'=>$s['folio'],'pdf_url'=>'supervision-report.php?id='.$s['id']];}
 public function comment(array$a,array$in):array{$this->auth->require($a,'supervisions.manage');$s=$this->scoped($a,(int)($in['supervision_id']??0));$comment=$this->text((string)($in['comment']??''),'El comentario',10,1500);$this->repo->comment((int)$s['id'],(int)$a['id'],$comment);$this->audit($a,'supervisions.commented',['supervision_id'=>$s['id']]);return[];}
 public function setPin(array$a,array$in):array{$this->auth->require($a,'supervisions.manage');$password=(string)($in['password']??'');$pin=(string)($in['pin']??'');$confirm=(string)($in['pin_confirmation']??'');if(!password_verify($password,(string)$a['password_hash']))throw new HttpException('La contraseña actual no es correcta.',422);if(!preg_match('/^\d{6}$/',$pin)||$pin!==$confirm||preg_match('/^(\d)\1{5}$/',$pin))throw new HttpException('El PIN debe contener seis dígitos, coincidir y no repetir un solo número.',422);$this->repo->updateActorPin((int)$a['id'],password_hash($pin,PASSWORD_DEFAULT));$this->audit($a,'supervisions.pin_changed',[]);return[];}
 public function report(array$a,int$id):array{return$this->detail($a,$id);}
 private function location(array$a,int$id):array{$l=$this->repo->locationClient($id);if(!$l||!$this->repo->inScope($a,$id))throw new HttpException('El lugar no existe o está fuera de tu alcance.',404);return$l;}
 private function points(int$l,mixed$raw):array{$p=is_array($raw)?array_values(array_unique(array_filter(array_map('intval',$raw)))):[];if(!$this->repo->validPoints($l,$p))throw new HttpException('Selecciona uno o varios puntos válidos del lugar.',422);return$p;}
 private function scoped(array$a,int$id):array{$s=$this->repo->supervision($id);if(!$s||!$this->repo->inScope($a,(int)$s['location_id']))throw new HttpException('La supervisión no existe o está fuera de tu alcance.',404);return$s;}
 private function text(string$v,string$l,int$min,int$max):string{$v=trim($v);$n=mb_strlen($v);if($n<$min||$n>$max)throw new HttpException("$l debe contener entre $min y $max caracteres.",422);return$v;}
 private function audit(array$a,string$event,array$c):void{$this->logs->record((int)$a['id'],$event,ClientInfo::ip(),ClientInfo::userAgent(),$c);}
}
