<?php
declare(strict_types=1);

return static function(PDO $pdo,bool $demo=false):void{
    if(!$demo)return;
    $companyId=(int)$pdo->query('SELECT id FROM surveillance_companies ORDER BY id LIMIT 1')->fetchColumn();$roleId=(int)$pdo->query("SELECT id FROM roles WHERE code='guard'")->fetchColumn();if(!$companyId||!$roleId)return;
    $root=dirname(__DIR__,2);$photoDir=$root.'/storage/guards/photos';if(!is_dir($photoDir))mkdir($photoDir,0775,true);$photo='storage/guards/photos/demo-guard.png';if(!is_file($root.'/'.$photo))file_put_contents($root.'/'.$photo,base64_decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII='));
    $guards=[
        ['vigilante@demo.local','Carlos Mendoza','VIG-001','8111001001','246810'],
        ['vigilante2@demo.local','Mariana Torres','VIG-002','8111001002','135790'],
    ];
    $user=$pdo->prepare("INSERT INTO users(surveillance_company_id,role_id,full_name,email,password_hash,password_changed_at,is_active,theme_preference,force_password_change,created_at,updated_at) VALUES(?,?,?,?,?,UTC_TIMESTAMP(),1,'auto',0,UTC_TIMESTAMP(),UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE full_name=VALUES(full_name),role_id=VALUES(role_id),is_active=1,updated_at=UTC_TIMESTAMP()");
    $profile=$pdo->prepare("INSERT INTO guard_profiles(user_id,employee_number,photo_path,phone,address_line,hire_date,emergency_contact_name,emergency_contact_phone,pin_hash,status,created_at,updated_at) VALUES(?,?,?,?,?,CURRENT_DATE,?,?,?,'active',UTC_TIMESTAMP(),UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE employee_number=VALUES(employee_number),photo_path=VALUES(photo_path),phone=VALUES(phone),status='active',updated_at=UTC_TIMESTAMP()");
    $guardIds=[];foreach($guards as[$email,$name,$employee,$phone,$pin]){$user->execute([$companyId,$roleId,$name,$email,password_hash('Ccserv-10.02!',PASSWORD_DEFAULT)]);$s=$pdo->prepare('SELECT id FROM users WHERE email=?');$s->execute([$email]);$id=(int)$s->fetchColumn();$guardIds[]=$id;$profile->execute([$id,$employee,$photo,$phone,'Domicilio de demostración','Central de monitoreo','8110000000',password_hash($pin,PASSWORD_DEFAULT)]);$active=$pdo->prepare("SELECT id,qr_asset_path FROM guard_credentials WHERE guard_user_id=? AND status='active' ORDER BY id DESC LIMIT 1");$active->execute([$id]);$current=$active->fetch();$hasQr=$current&&!empty($current['qr_asset_path'])&&is_file($root.'/'.$current['qr_asset_path']);if(!$hasQr){if($current)$pdo->prepare("UPDATE guard_credentials SET status='revoked',revoked_at=UTC_TIMESTAMP() WHERE id=?")->execute([$current['id']]);$token=bin2hex(random_bytes(32));$pdo->prepare("INSERT INTO guard_credentials(guard_user_id,token_hash,token_reference,status,issued_at,regenerated_from_id,created_at) VALUES(?,?,?,'active',UTC_TIMESTAMP(),?,UTC_TIMESTAMP())")->execute([$id,hash('sha256',$token),substr($token,0,12),$current['id']??null]);$credential=(int)$pdo->lastInsertId();if(class_exists(\Vigilancia\Services\CredentialAssetService::class)){$path=(new \Vigilancia\Services\CredentialAssetService($root))->createQr($token,$credential);if($path)$pdo->prepare('UPDATE guard_credentials SET qr_asset_path=? WHERE id=?')->execute([$path,$credential]);}}}
    $clientId=(int)$pdo->query("SELECT id FROM clients WHERE surveillance_company_id=$companyId ORDER BY id LIMIT 1")->fetchColumn();if(!$clientId)return;$north=(int)$pdo->query("SELECT id FROM locations WHERE client_id=$clientId ORDER BY id LIMIT 1")->fetchColumn();$south=(int)$pdo->query("SELECT id FROM locations WHERE client_id=$clientId ORDER BY id DESC LIMIT 1")->fetchColumn();if(!$north)return;$south=$south?:$north;
    $makeShift=static function(string$name,string$start,string$end,array$locations)use($pdo,$companyId):int{$q=$pdo->prepare('SELECT id FROM shifts WHERE surveillance_company_id=? AND name=? LIMIT 1');$q->execute([$companyId,$name]);$id=(int)$q->fetchColumn();if(!$id){$pdo->prepare("INSERT INTO shifts(surveillance_company_id,name,start_time,end_time,crosses_midnight,tolerance_minutes,early_departure_tolerance_minutes,overtime_after_minutes,applicable_days,is_active,created_at,updated_at) VALUES(?,?,?,?,?,10,5,15,'[1,2,3,4,5,6,7]',1,UTC_TIMESTAMP(),UTC_TIMESTAMP())")->execute([$companyId,$name,$start,$end,$end<=$start?1:0]);$id=(int)$pdo->lastInsertId();}foreach(array_unique($locations)as$l)$pdo->prepare("INSERT INTO shift_locations(shift_id,location_id,is_active,created_at) VALUES(?,?,1,UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE is_active=1")->execute([$id,$l]);return$id;};
    $day=$makeShift('Turno diurno 12x12','07:00','19:00',[$north,$south]);$night=$makeShift('Turno nocturno 12x12','19:00','07:00',[$north,$south]);
    $assignments=[[$guardIds[0],$north,$day,'12x12'],[$guardIds[1],$south,$night,'12x12']];foreach($assignments as[$guardId,$location,$shift,$pattern]){$point=(int)$pdo->query("SELECT id FROM access_points WHERE location_id=$location ORDER BY id LIMIT 1")->fetchColumn();if(!$point)continue;$q=$pdo->prepare("SELECT COUNT(*) FROM guard_assignments WHERE guard_user_id=? AND status='active'");$q->execute([$guardId]);if(!(int)$q->fetchColumn())$pdo->prepare("INSERT INTO guard_assignments(guard_user_id,client_id,location_id,access_point_id,shift_id,start_date,applicable_days,assignment_type,rotation_pattern,status,created_at,updated_at) VALUES(?,?,?,?,?,CURRENT_DATE,'[1,2,3,4,5,6,7]','rotation',?,'active',UTC_TIMESTAMP(),UTC_TIMESTAMP())")->execute([$guardId,$clientId,$location,$point,$shift,$pattern]);$pdo->prepare("INSERT INTO user_access_point_scopes(user_id,access_point_id,is_active,created_at,updated_at) VALUES(?,?,1,UTC_TIMESTAMP(),UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE is_active=1,updated_at=UTC_TIMESTAMP()")->execute([$guardId,$point]);}
};
