<?php
declare(strict_types=1);
$root=require dirname(__DIR__).'/bootstrap/app.php';
use Vigilancia\Middleware\CsrfMiddleware;
use Vigilancia\Support\Session;
Session::start();if(empty($_SESSION['operational_session_id'])){header('Location: guard-access.php');exit;}$csrf=CsrfMiddleware::token();
?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="<?=htmlspecialchars($csrf)?>"><title>Portal del vigilante · Sistema de Vigilancia</title><link rel="stylesheet" href="assets/css/styles.css"><link rel="stylesheet" href="assets/css/phase5.css"><link rel="stylesheet" href="assets/css/guard-portal.css?v=5.0.2"></head><body class="guard-portal-body">
<div class="guard-portal">
 <aside class="guard-portal-sidebar"><a class="guard-portal-brand" href="#inicio"><img src="assets/images/logo.svg" alt=""><span><strong>Sistema de Vigilancia</strong><small>Portal del vigilante</small></span></a><nav aria-label="Portal operativo"><button class="active" data-guard-view="inicio" type="button"><span>⌂</span> Inicio</button><button data-guard-view="turno" type="button"><span>◷</span> Mi turno</button><button data-guard-view="recorridos" type="button"><span>⌁</span> Recorridos</button><button data-guard-view="salida" type="button"><span>⇥</span> Cerrar turno</button></nav><div class="guard-scope-mini"><span class="live-dot"></span><strong>Sesión activa</strong><small id="sidebarPoint">Cargando punto…</small></div></aside>
 <main class="guard-portal-main"><header class="guard-portal-top"><button id="guardMenu" class="mobile-menu" type="button" aria-label="Abrir menú">☰</button><div><p class="eyebrow">OPERACIÓN EN PUNTO</p><h1 id="portalTitle">Portal del vigilante</h1></div><div class="guard-identity"><span id="guardInitials">VG</span><div><strong id="guardName">Cargando…</strong><small>Vigilante</small></div></div></header>
  <section class="guard-view" data-guard-section="inicio"><article class="guard-welcome"><div><p class="eyebrow">SESIÓN OPERATIVA ACTIVA</p><h2>Bienvenido al portal operativo</h2><p id="sessionScope">Validando el alcance de la sesión…</p></div><span class="live-pill">● En línea</span></article><div id="sessionMetrics" class="session-metrics"></div><section class="guard-module-grid"><button data-open-module="turno" type="button"><span>✓</span><strong>Mi turno</strong><small>Consulta entrada y clasificación</small></button><button data-open-module="recorridos" type="button"><span>⌁</span><strong>Recorridos</strong><small>Acceso al módulo operativo</small></button><button data-open-module="salida" type="button"><span>⇥</span><strong>Cerrar turno</strong><small>Registra tu salida mediante QR</small></button></section><div class="scope-notice">Tu operación queda restringida al cliente, lugar y punto de acceso de esta sesión.</div></section>
  <section class="guard-view" data-guard-section="turno" hidden><article class="operational-card"><p class="eyebrow">ASISTENCIA</p><h2>Información de mi turno</h2><div id="shiftDetails" class="session-metrics"></div><div class="scope-notice">La fotografía de entrada y los datos del dispositivo ya quedaron registrados.</div></article></section>
  <section class="guard-view" data-guard-section="recorridos" hidden><article class="operational-card"><p class="eyebrow">MÓDULO OPERATIVO</p><h2>Recorridos</h2><div class="module-stage"><span>⌁</span><div><h3>Acceso preparado dentro del portal</h3><p>La ejecución de recorridos incluirá inicio, evidencia, finalización y observaciones obligatorias en la Fase 8.</p></div></div><button class="submit" type="button" disabled title="Disponible al implementar la Fase 8">Iniciar recorrido</button></article></section>
  <section class="guard-view" data-guard-section="salida" hidden><article class="operational-card close-session"><p class="eyebrow">FINALIZAR OPERACIÓN</p><h2>Cerrar turno</h2><p>Escanea nuevamente tu credencial QR o escribe la referencia manual para registrar la salida.</p><label>QR o referencia manual<input id="closeToken" maxlength="64" autocomplete="off"></label><video id="closeCamera" autoplay playsinline muted hidden></video><canvas id="closeCanvas" hidden></canvas><div class="close-actions"><button class="ghost-button" id="scanCloseQr" type="button">Escanear QR con cámara</button><button class="submit" id="closeSession" type="button">Registrar salida y cerrar</button></div><div id="closeMessage" class="form-message" role="alert"></div></article></section>
 </main>
</div><script src="https://cdn.jsdelivr.net/npm/jsqr@1.4.0/dist/jsQR.js"></script><script src="assets/js/guard-operation.js?v=5.0.2"></script><script src="assets/js/qr-camera-fallback.js?v=5.0.3"></script></body></html>
