<?php
declare(strict_types=1);
$root=require dirname(__DIR__).'/bootstrap/app.php';
use Dompdf\Dompdf;use Dompdf\Options;use Vigilancia\Database\Connection;use Vigilancia\Repositories\PermissionRepository;use Vigilancia\Repositories\ReportRepository;use Vigilancia\Repositories\SecurityLogRepository;use Vigilancia\Services\AuthService;use Vigilancia\Services\ReportService;use Vigilancia\Support\ClientInfo;use Vigilancia\Support\Config;use Vigilancia\Support\Session;
Session::start();$pdo=Connection::make(Config::database());$auth=new AuthService($pdo);$actor=$auth->current();$service=new ReportService(new ReportRepository($pdo),new PermissionRepository($pdo),new SecurityLogRepository($pdo));$data=$service->report($actor,(int)($_GET['id']??0));$r=$data['report'];$e=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');
$rows=$data['rows'];$headers=$rows?array_keys($rows[0]):[];$table='<p class="muted">Sin registros para los filtros seleccionados.</p>';if($rows){$table='<table><thead><tr>'.implode('',array_map(fn($h)=>'<th>'.$e(str_replace('_',' ',$h)).'</th>',$headers)).'</tr></thead><tbody>';foreach($rows as$row){$table.='<tr>';foreach($headers as$h)$table.='<td>'.$e(is_scalar($row[$h]??null)?$row[$h]:'').'</td>';$table.='</tr>';}$table.='</tbody></table>';}
$appUrl=Config::app()['url'];$evidence='';foreach(array_slice($data['evidence'],0,30)as$file){$path=$root.'/'.$file['file_path'];if($file['media_type']==='photo'&&is_file($path))$evidence.='<figure><img src="data:'.$file['mime_type'].';base64,'.base64_encode((string)file_get_contents($path)).'"><figcaption>Evento #'.$e($file['event_id']).' · '.$e($file['captured_at']).'</figcaption></figure>';else$evidence.='<p>Video del evento #'.$e($file['event_id']).': <a href="'.$e($appUrl.'/event-evidence.php?id='.$file['id']).'">enlace protegido</a></p>';}
$logo=is_file($root.'/public/assets/images/logo.svg')?'data:image/svg+xml;base64,'.base64_encode((string)file_get_contents($root.'/public/assets/images/logo.svg')):'';
$html='<!doctype html><html lang="es"><head><meta charset="utf-8"><style>@page{margin:28px 22px}body{font-family:DejaVu Sans,sans-serif;color:#0B1D3A;font-size:8px}header{background:#0B1D3A;color:#fff;padding:16px}header img{width:44px;float:right}h1{margin:0;font-size:19px}.meta{font-size:9px;margin:12px 0}table{width:100%;border-collapse:collapse;page-break-inside:auto}tr{page-break-inside:avoid}th{background:#163D7A;color:#fff}th,td{padding:5px;border:1px solid #d7dee9;text-align:left;word-break:break-word}.muted{color:#486A92}figure{display:inline-block;width:30%;margin:1%}figure img{width:100%;height:130px;object-fit:cover}</style></head><body><header>'.($logo?'<img src="'.$logo.'">':'').'<h1>Sistema de Vigilancia · '.$e($data['title']).'</h1><p>Acceso seguro con código QR</p></header><div class="meta"><strong>Folio:</strong> '.$e($r['folio']).' · <strong>Generado:</strong> '.$e($r['generated_at']).' UTC · <strong>Usuario:</strong> '.$e($r['generated_by_name']).'<br><strong>Periodo:</strong> '.$e($data['filters']['date_from']).' a '.$e($data['filters']['date_to']).'</div>'.$table.($evidence?'<h2>Evidencias</h2><div>'.$evidence.'</div>':'').'</body></html>';
$options=new Options();$options->set('isRemoteEnabled',false);$dompdf=new Dompdf($options);$dompdf->loadHtml($html,'UTF-8');$dompdf->setPaper('letter','landscape');$dompdf->render();$canvas=$dompdf->getCanvas();$canvas->page_text($canvas->get_width()-100,$canvas->get_height()-18,'Página {PAGE_NUM} de {PAGE_COUNT}',null,7,[0.04,0.11,0.23]);(new SecurityLogRepository($pdo))->record((int)$actor['id'],'reports.downloaded',ClientInfo::ip(),ClientInfo::userAgent(),['record_type'=>'report','record_id'=>$r['id'],'folio'=>$r['folio']]);$dompdf->stream($r['folio'].'.pdf',['Attachment'=>false]);
