<?php
declare(strict_types=1);
$root=require dirname(__DIR__).'/bootstrap/app.php';
use Vigilancia\Database\Connection;use Vigilancia\Middleware\CsrfMiddleware;use Vigilancia\Repositories\PermissionRepository;use Vigilancia\Services\AuthService;use Vigilancia\Services\AuthorizationService;use Vigilancia\Services\ScopeService;use Vigilancia\Support\Config;use Vigilancia\Support\Session;
Session::start();$pdo=Connection::make(Config::database());$auth=new AuthService($pdo);$actor=$auth->current();$type=($_GET['type']??'visit')==='provider'?'provider':'visit';$id=(int)($_GET['id']??0);
if($type==='visit'){$s=$pdo->prepare('SELECT vp.id,vp.resident_user_id owner_id,vp.location_id,vp.visitor_name display_name,vp.qr_reference,vp.qr_asset_path,u.name unit_name,l.name location_name FROM visitor_passes vp JOIN units u ON u.id=vp.unit_id JOIN locations l ON l.id=vp.location_id WHERE vp.id=?');}
else{$s=$pdo->prepare('SELECT pa.id,COALESCE(pa.resident_user_id,pa.created_by) owner_id,pa.location_id,pa.responsible_name display_name,pa.qr_reference,pa.qr_asset_path,COALESCE(u.name,\'Sin unidad\') unit_name,l.name location_name FROM provider_accesses pa LEFT JOIN units u ON u.id=pa.unit_id JOIN locations l ON l.id=pa.location_id WHERE pa.id=?');}$s->execute([$id]);$row=$s->fetch();if(!$row){http_response_code(404);exit('QR no encontrado.');}
$allowed=(int)$row['owner_id']===(int)$actor['id'];if(!$allowed&&in_array($actor['role_code'],['superadmin','admin','supervisor'],true)){$permission=$type==='visit'?'visits.view':'providers.manage';try{(new AuthorizationService(new PermissionRepository($pdo)))->require($actor,$permission);$allowed=(new ScopeService($pdo))->location($actor,(int)$row['location_id']);}catch(Throwable){$allowed=false;}}if(!$allowed){http_response_code(403);exit('Acceso denegado.');}
$path=$row['qr_asset_path']?$root.'/'.$row['qr_asset_path']:'';if(!$path||!is_file($path)){http_response_code(404);exit('La imagen QR no está disponible.');}$mime=(new finfo(FILEINFO_MIME_TYPE))->file($path)?:'image/svg+xml';
if(isset($_GET['raw'])){header('Content-Type: '.$mime);header('Content-Disposition: '.(isset($_GET['download'])?'attachment':'inline').'; filename="qr-'.$type.'-'.$id.'.'.($mime==='image/png'?'png':'svg').'"');header('Cache-Control: private, no-store');readfile($path);exit;}
$csrf=CsrfMiddleware::token();
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="<?=htmlspecialchars($csrf)?>"><title>Código QR de acceso</title><link rel="stylesheet" href="assets/css/styles.css"><link rel="stylesheet" href="assets/css/phase7.css"><style>.qr-sheet{max-width:520px;margin:30px auto;text-align:center}.qr-sheet img{width:min(360px,90%);background:#fff;padding:16px;border-radius:18px}.qr-actions{display:flex;justify-content:center;gap:8px;flex-wrap:wrap;margin-top:18px}</style></head><body><main class="qr-sheet security-card"><p class="eyebrow">ACCESO SEGURO CON CÓDIGO QR</p><h1><?=htmlspecialchars($row['display_name'])?></h1><p><?=htmlspecialchars($row['location_name'].' · '.$row['unit_name'])?></p><img id="qrImage" src="?type=<?=urlencode($type)?>&amp;id=<?=$id?>&amp;raw=1" alt="Código QR"><p><strong>Referencia:</strong> <?=htmlspecialchars((string)$row['qr_reference'])?></p><div class="qr-actions"><a class="ghost-button" href="?type=<?=urlencode($type)?>&amp;id=<?=$id?>&amp;raw=1&amp;download=1" id="downloadQr">Descargar imagen</a><button class="submit" type="button" id="nativeShare">Compartir</button><button class="ghost-button" type="button" id="whatsappShare">Abrir WhatsApp</button></div><p class="muted">WhatsApp abrirá un mensaje preparado. Adjunta la imagen descargada; el sistema no afirma que haya sido enviada.</p></main><script>const csrf=document.querySelector('meta[name="csrf-token"]').content,type=<?=json_encode($type)?>,id=<?=$id?>;async function log(channel){if(type!=='visit')return;await fetch('api/visits/action',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({id,action:'share',channel})}).catch(()=>{})}document.querySelector('#downloadQr').onclick=()=>log('download');document.querySelector('#nativeShare').onclick=async()=>{await log('native');const response=await fetch(`?type=${type}&id=${id}&raw=1`),blob=await response.blob(),file=new File([blob],`qr-${type}-${id}.${blob.type==='image/png'?'png':'svg'}`,{type:blob.type});if(navigator.share&&navigator.canShare?.({files:[file]}))await navigator.share({title:'Acceso autorizado',text:'Presenta este código QR en el acceso.',files:[file]});else alert('Tu navegador no permite compartir archivos. Usa Descargar imagen.')};document.querySelector('#whatsappShare').onclick=async()=>{await log('whatsapp');window.open('https://wa.me/?text='+encodeURIComponent('Te comparto un acceso autorizado. Adjuntaré la imagen QR en este chat.'),'_blank')};</script></body></html>
