<?php
declare(strict_types=1); use PDO;
return static function(PDO $pdo):void{$sql=[
"CREATE TABLE IF NOT EXISTS roles (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, code VARCHAR(50) NOT NULL UNIQUE, name VARCHAR(100) NOT NULL, description VARCHAR(255) NULL, is_active TINYINT(1) NOT NULL DEFAULT 1, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
"CREATE TABLE IF NOT EXISTS permissions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, code VARCHAR(100) NOT NULL UNIQUE, module VARCHAR(60) NOT NULL, action VARCHAR(60) NOT NULL, name VARCHAR(120) NOT NULL, created_at DATETIME NOT NULL, INDEX idx_permissions_module_action(module,action)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
"CREATE TABLE IF NOT EXISTS surveillance_companies (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(180) NOT NULL, legal_name VARCHAR(180) NULL, timezone VARCHAR(80) NOT NULL DEFAULT 'America/Mexico_City', is_active TINYINT(1) NOT NULL DEFAULT 1, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
"CREATE TABLE IF NOT EXISTS users (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, surveillance_company_id BIGINT UNSIGNED NOT NULL, role_id BIGINT UNSIGNED NOT NULL, full_name VARCHAR(180) NOT NULL, email VARCHAR(190) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, password_changed_at DATETIME NOT NULL, failed_attempts SMALLINT UNSIGNED NOT NULL DEFAULT 0, locked_until DATETIME NULL, is_active TINYINT(1) NOT NULL DEFAULT 1, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, CONSTRAINT fk_users_company FOREIGN KEY(surveillance_company_id) REFERENCES surveillance_companies(id), CONSTRAINT fk_users_role FOREIGN KEY(role_id) REFERENCES roles(id), INDEX idx_users_company_active(surveillance_company_id,is_active)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
"CREATE TABLE IF NOT EXISTS user_sessions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, session_token_hash CHAR(64) NOT NULL UNIQUE, ip_address VARCHAR(45) NULL, user_agent VARCHAR(500) NULL, last_activity_at DATETIME NOT NULL, expires_at DATETIME NOT NULL, revoked_at DATETIME NULL, created_at DATETIME NOT NULL, CONSTRAINT fk_sessions_user FOREIGN KEY(user_id) REFERENCES users(id), INDEX idx_sessions_user_expiry(user_id,expires_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
"CREATE TABLE IF NOT EXISTS role_permissions (role_id BIGINT UNSIGNED NOT NULL, permission_id BIGINT UNSIGNED NOT NULL, created_at DATETIME NOT NULL, PRIMARY KEY(role_id,permission_id), CONSTRAINT fk_rp_role FOREIGN KEY(role_id) REFERENCES roles(id), CONSTRAINT fk_rp_permission FOREIGN KEY(permission_id) REFERENCES permissions(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
"CREATE TABLE IF NOT EXISTS user_permissions (user_id BIGINT UNSIGNED NOT NULL, permission_id BIGINT UNSIGNED NOT NULL, is_allowed TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, PRIMARY KEY(user_id,permission_id), CONSTRAINT fk_up_user FOREIGN KEY(user_id) REFERENCES users(id), CONSTRAINT fk_up_permission FOREIGN KEY(permission_id) REFERENCES permissions(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
"CREATE TABLE IF NOT EXISTS system_settings (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, setting_key VARCHAR(120) NOT NULL UNIQUE, setting_value TEXT NULL, value_type VARCHAR(20) NOT NULL DEFAULT 'string', is_public TINYINT(1) NOT NULL DEFAULT 0, updated_by BIGINT UNSIGNED NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, CONSTRAINT fk_settings_user FOREIGN KEY(updated_by) REFERENCES users(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
"CREATE TABLE IF NOT EXISTS security_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NULL, event_type VARCHAR(80) NOT NULL, ip_address VARCHAR(45) NULL, user_agent VARCHAR(500) NULL, context_json JSON NULL, occurred_at DATETIME NOT NULL, CONSTRAINT fk_security_user FOREIGN KEY(user_id) REFERENCES users(id), INDEX idx_security_event_date(event_type,occurred_at), INDEX idx_security_user_date(user_id,occurred_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
"CREATE TABLE IF NOT EXISTS installer_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, step VARCHAR(80) NOT NULL, status VARCHAR(20) NOT NULL, message VARCHAR(500) NOT NULL, context_json JSON NULL, created_at DATETIME NOT NULL, INDEX idx_installer_status_date(status,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"
];foreach($sql as $statement)$pdo->exec($statement);};
