<?php
declare(strict_types=1);
return static function (PDO $pdo): void {
    $pdo->exec("CREATE TABLE IF NOT EXISTS offline_devices(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,guard_user_id BIGINT UNSIGNED NOT NULL,device_identifier CHAR(64) NOT NULL,sync_token_hash CHAR(64) NOT NULL UNIQUE,status VARCHAR(20) NOT NULL DEFAULT 'active',authorized_at DATETIME NOT NULL,expires_at DATETIME NOT NULL,last_sync_at DATETIME NULL,revoked_at DATETIME NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,CONSTRAINT fk_offline_device_guard FOREIGN KEY(guard_user_id) REFERENCES users(id),UNIQUE KEY uq_offline_guard_device(guard_user_id,device_identifier),INDEX idx_offline_device_active(status,expires_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    $pdo->exec("CREATE TABLE IF NOT EXISTS offline_operations(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,client_uuid CHAR(36) NOT NULL UNIQUE,offline_device_id BIGINT UNSIGNED NOT NULL,guard_user_id BIGINT UNSIGNED NOT NULL,operational_session_id BIGINT UNSIGNED NULL,client_id BIGINT UNSIGNED NULL,location_id BIGINT UNSIGNED NULL,access_point_id BIGINT UNSIGNED NULL,operation_type VARCHAR(40) NOT NULL,entity_key VARCHAR(120) NULL,payload_json JSON NOT NULL,evidence_path VARCHAR(255) NULL,occurred_at DATETIME NOT NULL,received_at DATETIME NOT NULL,expires_at DATETIME NOT NULL,status VARCHAR(24) NOT NULL,conflict_group CHAR(36) NULL,reviewed_by BIGINT UNSIGNED NULL,review_comment VARCHAR(500) NULL,reviewed_at DATETIME NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,CONSTRAINT fk_offline_operation_device FOREIGN KEY(offline_device_id) REFERENCES offline_devices(id),CONSTRAINT fk_offline_operation_guard FOREIGN KEY(guard_user_id) REFERENCES users(id),CONSTRAINT fk_offline_operation_session FOREIGN KEY(operational_session_id) REFERENCES operational_sessions(id),CONSTRAINT fk_offline_operation_client FOREIGN KEY(client_id) REFERENCES clients(id),CONSTRAINT fk_offline_operation_location FOREIGN KEY(location_id) REFERENCES locations(id),CONSTRAINT fk_offline_operation_point FOREIGN KEY(access_point_id) REFERENCES access_points(id),CONSTRAINT fk_offline_operation_reviewer FOREIGN KEY(reviewed_by) REFERENCES users(id),INDEX idx_offline_review(status,received_at),INDEX idx_offline_scope(location_id,status),INDEX idx_offline_entity(entity_key,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");

    $pdo->exec("INSERT INTO permissions(code,module,action,name,created_at) VALUES('offline_operations.capture','offline_operations','capture','Registrar operaciones sin conexión',UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name)");
    $pdo->exec("INSERT IGNORE INTO role_permissions(role_id,permission_id,created_at) SELECT r.id,p.id,UTC_TIMESTAMP() FROM roles r JOIN permissions p ON p.code='offline_operations.capture' WHERE r.code IN ('superadmin','guard')");
};
