<?php
declare(strict_types=1);

return static function(PDO $pdo):void{
    $column=(int)$pdo->query("SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='users' AND COLUMN_NAME='confirmation_pin_hash'")->fetchColumn();
    if(!$column)$pdo->exec("ALTER TABLE users ADD confirmation_pin_hash VARCHAR(255) NULL AFTER password_hash");
    foreach([
        "CREATE TABLE IF NOT EXISTS supervision_schedules (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,client_id BIGINT UNSIGNED NOT NULL,location_id BIGINT UNSIGNED NOT NULL,frequency VARCHAR(20) NOT NULL,scheduled_at DATETIME NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'pending',created_by BIGINT UNSIGNED NOT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,CONSTRAINT fk_sup_schedule_client FOREIGN KEY(client_id) REFERENCES clients(id),CONSTRAINT fk_sup_schedule_location FOREIGN KEY(location_id) REFERENCES locations(id),CONSTRAINT fk_sup_schedule_creator FOREIGN KEY(created_by) REFERENCES users(id),INDEX idx_sup_schedule_pending(status,scheduled_at),INDEX idx_sup_schedule_scope(location_id,scheduled_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS supervision_schedule_points (schedule_id BIGINT UNSIGNED NOT NULL,access_point_id BIGINT UNSIGNED NOT NULL,PRIMARY KEY(schedule_id,access_point_id),CONSTRAINT fk_sup_sp_schedule FOREIGN KEY(schedule_id) REFERENCES supervision_schedules(id),CONSTRAINT fk_sup_sp_point FOREIGN KEY(access_point_id) REFERENCES access_points(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS supervisions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,folio VARCHAR(40) NOT NULL UNIQUE,schedule_id BIGINT UNSIGNED NULL,client_id BIGINT UNSIGNED NOT NULL,location_id BIGINT UNSIGNED NOT NULL,supervisor_user_id BIGINT UNSIGNED NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'in_progress',observations TEXT NULL,started_at DATETIME NOT NULL,completed_at DATETIME NULL,supervisor_confirmation_name VARCHAR(180) NULL,supervisor_confirmed_at DATETIME NULL,responsible_user_id BIGINT UNSIGNED NULL,responsible_confirmation_name VARCHAR(180) NULL,responsible_confirmed_at DATETIME NULL,responsible_absent TINYINT(1) NOT NULL DEFAULT 0,absence_reason VARCHAR(500) NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,CONSTRAINT fk_supervision_schedule FOREIGN KEY(schedule_id) REFERENCES supervision_schedules(id),CONSTRAINT fk_supervision_client FOREIGN KEY(client_id) REFERENCES clients(id),CONSTRAINT fk_supervision_location FOREIGN KEY(location_id) REFERENCES locations(id),CONSTRAINT fk_supervision_supervisor FOREIGN KEY(supervisor_user_id) REFERENCES users(id),CONSTRAINT fk_supervision_responsible FOREIGN KEY(responsible_user_id) REFERENCES users(id),INDEX idx_supervision_scope(location_id,status,started_at),INDEX idx_supervision_supervisor(supervisor_user_id,started_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS supervision_points (supervision_id BIGINT UNSIGNED NOT NULL,access_point_id BIGINT UNSIGNED NOT NULL,PRIMARY KEY(supervision_id,access_point_id),CONSTRAINT fk_supervision_point_supervision FOREIGN KEY(supervision_id) REFERENCES supervisions(id),CONSTRAINT fk_supervision_point_access FOREIGN KEY(access_point_id) REFERENCES access_points(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS supervision_evidence (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,supervision_id BIGINT UNSIGNED NOT NULL,uploaded_by BIGINT UNSIGNED NOT NULL,mime_type VARCHAR(80) NOT NULL,file_path VARCHAR(255) NOT NULL,file_size BIGINT UNSIGNED NOT NULL,watermark_text VARCHAR(500) NOT NULL,captured_at DATETIME NOT NULL,created_at DATETIME NOT NULL,CONSTRAINT fk_sup_evidence_supervision FOREIGN KEY(supervision_id) REFERENCES supervisions(id),CONSTRAINT fk_sup_evidence_user FOREIGN KEY(uploaded_by) REFERENCES users(id),INDEX idx_sup_evidence(supervision_id,captured_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS supervision_comments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,supervision_id BIGINT UNSIGNED NOT NULL,author_user_id BIGINT UNSIGNED NOT NULL,comment TEXT NOT NULL,created_at DATETIME NOT NULL,CONSTRAINT fk_sup_comment_supervision FOREIGN KEY(supervision_id) REFERENCES supervisions(id),CONSTRAINT fk_sup_comment_author FOREIGN KEY(author_user_id) REFERENCES users(id),INDEX idx_sup_comments(supervision_id,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"
    ]as$sql)$pdo->exec($sql);
    $p=$pdo->prepare("INSERT INTO permissions(code,module,action,name,created_at) VALUES(?,?,?,?,UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name)");
    foreach([['supervisions.manage','supervisions','manage','Ejecutar y consultar supervisiones'],['supervisions.schedule','supervisions','schedule','Programar supervisiones']]as$row)$p->execute($row);
    foreach(['superadmin','admin','supervisor']as$role){$codes=$role==='supervisor'?['supervisions.manage']:['supervisions.manage','supervisions.schedule'];$marks=implode(',',array_fill(0,count($codes),'?'));$s=$pdo->prepare("INSERT IGNORE INTO role_permissions(role_id,permission_id,created_at) SELECT r.id,p.id,UTC_TIMESTAMP() FROM roles r JOIN permissions p WHERE r.code=? AND p.code IN ($marks)");$s->execute(array_merge([$role],$codes));}
};
