<?php
declare(strict_types=1);
return static function(PDO$pdo):void{
 $columns=['module_name'=>'VARCHAR(80) NULL AFTER event_type','record_type'=>'VARCHAR(80) NULL AFTER module_name','record_id'=>'BIGINT UNSIGNED NULL AFTER record_type','old_values_json'=>'JSON NULL AFTER context_json','new_values_json'=>'JSON NULL AFTER old_values_json'];foreach($columns as$name=>$definition){$exists=(int)$pdo->query("SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='security_logs' AND column_name='$name'")->fetchColumn();if(!$exists)$pdo->exec("ALTER TABLE security_logs ADD $name $definition");}
 foreach([
  "CREATE TABLE IF NOT EXISTS report_generations (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,folio VARCHAR(50) NOT NULL UNIQUE,report_type VARCHAR(50) NOT NULL,filters_json JSON NOT NULL,generated_by BIGINT UNSIGNED NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'ready',generated_at DATETIME NOT NULL,CONSTRAINT fk_report_user FOREIGN KEY(generated_by) REFERENCES users(id),INDEX idx_reports_user_date(generated_by,generated_at),INDEX idx_reports_type_date(report_type,generated_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
  "CREATE TABLE IF NOT EXISTS attendance_absences (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,assignment_id BIGINT UNSIGNED NOT NULL,guard_user_id BIGINT UNSIGNED NOT NULL,shift_id BIGINT UNSIGNED NOT NULL,client_id BIGINT UNSIGNED NOT NULL,location_id BIGINT UNSIGNED NOT NULL,access_point_id BIGINT UNSIGNED NOT NULL,absence_date DATE NOT NULL,scheduled_start_at DATETIME NOT NULL,scheduled_end_at DATETIME NOT NULL,detected_at DATETIME NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'detected',CONSTRAINT fk_abs_assignment FOREIGN KEY(assignment_id) REFERENCES guard_assignments(id),CONSTRAINT fk_abs_guard FOREIGN KEY(guard_user_id) REFERENCES users(id),CONSTRAINT fk_abs_shift FOREIGN KEY(shift_id) REFERENCES shifts(id),CONSTRAINT fk_abs_client FOREIGN KEY(client_id) REFERENCES clients(id),CONSTRAINT fk_abs_location FOREIGN KEY(location_id) REFERENCES locations(id),CONSTRAINT fk_abs_point FOREIGN KEY(access_point_id) REFERENCES access_points(id),UNIQUE KEY uq_absence_assignment_date(assignment_id,absence_date),INDEX idx_absence_scope(location_id,absence_date)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
  "CREATE TABLE IF NOT EXISTS cron_runs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,task_name VARCHAR(100) NOT NULL,status VARCHAR(20) NOT NULL,started_at DATETIME NOT NULL,finished_at DATETIME NULL,duration_ms INT UNSIGNED NULL,result_json JSON NULL,error_message VARCHAR(1000) NULL,next_expected_at DATETIME NULL,INDEX idx_cron_task_date(task_name,started_at),INDEX idx_cron_status(status,started_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
  "CREATE TABLE IF NOT EXISTS storage_alerts (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,client_id BIGINT UNSIGNED NOT NULL,usage_bytes BIGINT UNSIGNED NOT NULL,limit_bytes BIGINT UNSIGNED NOT NULL,threshold_percent SMALLINT UNSIGNED NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'notified',notified_at DATETIME NOT NULL,resolved_at DATETIME NULL,CONSTRAINT fk_storage_alert_client FOREIGN KEY(client_id) REFERENCES clients(id),INDEX idx_storage_alert(client_id,status,notified_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
  "CREATE TABLE IF NOT EXISTS retention_actions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,client_id BIGINT UNSIGNED NOT NULL,asset_type VARCHAR(50) NOT NULL,record_id BIGINT UNSIGNED NOT NULL,file_path VARCHAR(255) NOT NULL,scheduled_delete_at DATETIME NOT NULL,notified_at DATETIME NOT NULL,deleted_at DATETIME NULL,status VARCHAR(20) NOT NULL DEFAULT 'notified',CONSTRAINT fk_retention_client FOREIGN KEY(client_id) REFERENCES clients(id),UNIQUE KEY uq_retention_asset(asset_type,record_id,file_path),INDEX idx_retention_due(status,scheduled_delete_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"
 ]as$sql)$pdo->exec($sql);
 $settings=[['reports.max_range_days','90','integer'],['retention.evidence_months','12','integer'],['retention.identification_days','90','integer'],['retention.warning_days','7','integer'],['storage.warning_percent','90','integer'],['cron.expected_interval_minutes','5','integer']];$s=$pdo->prepare("INSERT INTO system_settings(setting_key,setting_value,value_type,is_public,created_at,updated_at) VALUES(?,?,?,0,UTC_TIMESTAMP(),UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value),updated_at=UTC_TIMESTAMP()");foreach($settings as$row)$s->execute($row);
 foreach(['admin']as$role){$s=$pdo->prepare("INSERT IGNORE INTO role_permissions(role_id,permission_id,created_at) SELECT r.id,p.id,UTC_TIMESTAMP() FROM roles r JOIN permissions p ON p.code='audit.view' WHERE r.code=?");$s->execute([$role]);}
};
