<?php
declare(strict_types=1);

return [
    'permissions' => [
        ['clients.manage', 'clients', 'manage', 'Gestionar clientes'],
        ['locations.manage', 'locations', 'manage', 'Gestionar lugares'],
        ['locations.view', 'locations', 'view', 'Consultar lugares asignados'],
        ['access_points.manage', 'access_points', 'manage', 'Gestionar puntos de acceso'],
        ['access_points.view', 'access_points', 'view', 'Consultar puntos de acceso asignados'],
        ['units.manage', 'units', 'manage', 'Gestionar unidades'],
        ['units.view', 'units', 'view', 'Consultar unidades asignadas'],
        ['units.view_own', 'units', 'view_own', 'Consultar unidades propias'],
        ['users.manage', 'users', 'manage', 'Gestionar usuarios'],
        ['guards.manage', 'guards', 'manage', 'Gestionar vigilantes'],
        ['guards.view', 'guards', 'view', 'Consultar vigilantes asignados'],
        ['guards.credential', 'guards', 'credential', 'Emitir y revocar credenciales'],
        ['guards.pin_reset', 'guards', 'pin_reset', 'Restablecer PIN operativo'],
        ['residents.manage', 'residents', 'manage', 'Gestionar residentes'],
        ['shifts.manage', 'shifts', 'manage', 'Gestionar turnos'],
        ['shifts.view', 'shifts', 'view', 'Consultar turnos asignados'],
        ['shifts.novelty', 'shifts', 'novelty', 'Registrar novedades de turno'],
        ['assignments.manage', 'assignments', 'manage', 'Gestionar asignaciones'],
        ['assignments.view', 'assignments', 'view', 'Consultar asignaciones'],
        ['assignments.request_change', 'assignments', 'request_change', 'Solicitar cambios de asignación'],
        ['operations.view', 'operations', 'view', 'Consultar operación'],
        ['operational_sessions.close', 'operational_sessions', 'close', 'Cerrar sesiones operativas'],
        ['attendance.view', 'attendance', 'view', 'Consultar asistencias'],
        ['attendance.own', 'attendance', 'view_own', 'Consultar asistencia propia'],
        ['visits.manage', 'visits', 'manage_own', 'Gestionar visitas propias'],
        ['visits.view', 'visits', 'view', 'Consultar visitas autorizadas'],
        ['visits.check_in', 'visits', 'check_in', 'Registrar entrada y salida de visitas'],
        ['providers.manage', 'providers', 'manage', 'Gestionar accesos de proveedores'],
        ['providers.create', 'providers', 'create_own', 'Crear accesos propios de proveedores'],
        ['providers.check_in', 'providers', 'check_in', 'Registrar entrada y salida de proveedores'],
        ['access_identifications.view', 'access_identifications', 'view', 'Consultar identificaciones capturadas'],
        ['events.manage', 'events', 'manage', 'Administrar eventos'],
        ['events.review', 'events', 'review', 'Revisar y comentar eventos'],
        ['events.create', 'events', 'create', 'Registrar eventos'],
        ['rounds.view', 'rounds', 'view', 'Consultar recorridos'],
        ['rounds.review', 'rounds', 'review', 'Revisar recorridos'],
        ['rounds.execute', 'rounds', 'execute', 'Ejecutar recorridos'],
        ['supervisions.manage', 'supervisions', 'manage', 'Realizar supervisiones'],
        ['offline_conflicts.manage', 'offline_conflicts', 'manage', 'Resolver conflictos sin conexión'],
        ['offline_operations.capture', 'offline_operations', 'capture', 'Registrar operaciones sin conexión'],
        ['reports.view', 'reports', 'view', 'Consultar reportes operativos'],
        ['reports.own_history', 'reports', 'view_own', 'Consultar historial propio'],
        ['system.configure', 'system', 'configure', 'Configurar el sistema'],
        ['audit.view', 'audit', 'view', 'Consultar auditoría'],
        ['maintenance.manage', 'maintenance', 'manage', 'Ejecutar mantenimiento'],
        ['own_activity.view', 'own_activity', 'view', 'Consultar actividad propia'],
    ],
    'modules' => [
        'clientes' => ['label' => 'Clientes', 'icon' => '▱', 'eyebrow' => 'Estructura comercial', 'title' => 'Clientes', 'description' => 'Clientes atendidos por la empresa de vigilancia.', 'phase' => 3, 'permissions' => ['clients.manage']],
        'sitios' => ['label' => 'Lugares y puntos', 'icon' => '⌖', 'eyebrow' => 'Alcance territorial', 'title' => 'Lugares y puntos de acceso', 'description' => 'Instalaciones, puntos de acceso y unidades autorizadas.', 'phase' => 3, 'permissions' => ['locations.manage', 'locations.view', 'access_points.manage', 'access_points.view', 'units.manage', 'units.view']],
        'mis_unidades' => ['label' => 'Mis unidades', 'icon' => '⌂', 'eyebrow' => 'Residencia', 'title' => 'Mis unidades', 'description' => 'Casas, departamentos, lotes o naves relacionados con tu cuenta.', 'phase' => 3, 'roles' => ['resident'], 'permissions' => ['units.view_own']],
        'usuarios' => ['label' => 'Usuarios', 'icon' => '♙', 'eyebrow' => 'Administración', 'title' => 'Usuarios y personal', 'description' => 'Usuarios, vigilantes y residentes dentro del alcance permitido.', 'phase' => 3, 'permissions' => ['users.manage', 'guards.manage', 'guards.view', 'residents.manage']],
        'turnos' => ['label' => 'Turnos', 'icon' => '◷', 'eyebrow' => 'Planeación operativa', 'title' => 'Turnos y asignaciones', 'description' => 'Turnos, rotaciones y asignaciones del personal.', 'phase' => 4, 'roles' => ['superadmin', 'admin', 'supervisor'], 'permissions' => ['shifts.manage', 'shifts.view', 'shifts.novelty', 'assignments.manage', 'assignments.view']],
        'operacion' => ['label' => 'Operación', 'icon' => '◉', 'eyebrow' => 'Control en tiempo real', 'title' => 'Operación', 'description' => 'Sesiones operativas y actividad en los puntos de acceso.', 'phase' => 5, 'permissions' => ['operations.view', 'operational_sessions.close']],
        'asistencias' => ['label' => 'Asistencias', 'icon' => '✓', 'eyebrow' => 'Control de personal', 'title' => 'Asistencias', 'description' => 'Entradas, salidas y clasificación de asistencias.', 'phase' => 5, 'permissions' => ['attendance.view', 'attendance.own']],
        'visitas' => ['label' => 'Visitas', 'icon' => '◇', 'eyebrow' => 'Accesos temporales', 'title' => 'Visitas', 'description' => 'Autorizaciones y control de acceso para visitantes.', 'phase' => 7, 'permissions' => ['visits.manage', 'visits.view', 'visits.check_in']],
        'proveedores' => ['label' => 'Proveedores', 'icon' => '▣', 'eyebrow' => 'Servicios externos', 'title' => 'Proveedores', 'description' => 'Accesos y registros de proveedores.', 'phase' => 7, 'permissions' => ['providers.manage', 'providers.create', 'providers.check_in']],
        'eventos' => ['label' => 'Incidencias', 'icon' => '△', 'eyebrow' => 'Seguimiento operativo', 'title' => 'Incidencias y evidencias', 'description' => 'Registro auditable de incidencias, evidencias y comentarios operativos.', 'phase' => 8, 'permissions' => ['events.manage', 'events.review', 'events.create']],
        'recorridos' => ['label' => 'Recorridos', 'icon' => '⌁', 'eyebrow' => 'Verificación de sitio', 'title' => 'Recorridos', 'description' => 'Ejecución y revisión de recorridos de vigilancia.', 'phase' => 8, 'permissions' => ['rounds.view', 'rounds.review', 'rounds.execute']],
        'supervisiones' => ['label' => 'Supervisiones', 'icon' => '◎', 'eyebrow' => 'Control de calidad', 'title' => 'Supervisiones', 'description' => 'Revisión documentada de lugares, puntos y personal.', 'phase' => 9, 'permissions' => ['supervisions.manage']],
        'sincronizacion' => ['label' => 'Sincronización', 'icon' => '↻', 'eyebrow' => 'Operación sin conexión', 'title' => 'Conflictos de sincronización', 'description' => 'Resolución de registros capturados sin conexión.', 'phase' => 6, 'permissions' => ['offline_conflicts.manage']],
        'reportes' => ['label' => 'Reportes', 'icon' => '▤', 'eyebrow' => 'Información', 'title' => 'Reportes', 'description' => 'Reportes operativos e historial autorizado.', 'phase' => 11, 'permissions' => ['reports.view', 'reports.own_history']],
        'configuracion' => ['label' => 'Configuración', 'icon' => '⚙', 'eyebrow' => 'Parámetros', 'title' => 'Configuración', 'description' => 'Parámetros generales y operativos del sistema.', 'phase' => 3, 'permissions' => ['system.configure']],
        'auditoria' => ['label' => 'Auditoría', 'icon' => '◫', 'eyebrow' => 'Trazabilidad', 'title' => 'Auditoría', 'description' => 'Consulta de acciones sensibles y cambios administrativos.', 'phase' => 11, 'permissions' => ['audit.view']],
        'mantenimiento' => ['label' => 'Mantenimiento', 'icon' => '⌘', 'eyebrow' => 'Administración técnica', 'title' => 'Mantenimiento', 'description' => 'Procesos técnicos y conservación de la plataforma.', 'phase' => 11, 'permissions' => ['maintenance.manage']],
        'mi_actividad' => ['label' => 'Mi actividad', 'icon' => '◌', 'eyebrow' => 'Consulta personal', 'title' => 'Mi actividad', 'description' => 'Actividad operativa perteneciente al usuario autenticado.', 'phase' => 5, 'permissions' => ['own_activity.view']],
    ],
    'roles' => [
        'admin' => [
            'clients.manage', 'locations.manage', 'access_points.manage', 'units.manage',
            'users.manage', 'guards.manage', 'guards.credential', 'guards.pin_reset', 'residents.manage', 'shifts.manage',
            'assignments.manage', 'operations.view', 'attendance.view', 'visits.view',
            'providers.manage', 'access_identifications.view', 'events.manage', 'rounds.view', 'reports.view', 'system.configure',
        ],
        'supervisor' => [
            'locations.view', 'access_points.view', 'units.view', 'guards.view', 'shifts.view', 'assignments.view', 'assignments.request_change', 'operations.view',
            'operational_sessions.close', 'attendance.view', 'visits.view', 'providers.manage',
            'access_identifications.view', 'events.review', 'rounds.review', 'supervisions.manage', 'offline_conflicts.manage',
            'reports.view',
        ],
        'guard' => [
            'shifts.view', 'shifts.novelty', 'operations.view', 'attendance.own',
            'visits.check_in', 'providers.check_in', 'events.create', 'rounds.execute',
            'own_activity.view', 'offline_operations.capture',
        ],
        'resident' => ['units.view_own', 'visits.manage', 'providers.create', 'reports.own_history'],
    ],
];
