<?php
declare(strict_types=1);
namespace Vigilancia\Tests\Unit;
use PHPUnit\Framework\TestCase;
final class PhaseTwelveReleaseTest extends TestCase
{
 public function testIntegracionVisualFinalIncluyeAccesibilidadYResponsive():void{$root=dirname(__DIR__,2);$page=file_get_contents($root.'/public/index.php');$css=file_get_contents($root.'/public/assets/css/phase12.css');$js=file_get_contents($root.'/public/assets/js/app.js');$phase3=file_get_contents($root.'/public/assets/js/phase3.js');$phase4=file_get_contents($root.'/public/assets/js/phase4.js');self::assertStringContainsString('class="skip-link"',$page);self::assertStringContainsString('id="mainContent"',$page);self::assertStringContainsString('sidebarBackdrop',$js);self::assertStringContainsString('@media (max-width: 620px)',$css);self::assertStringContainsString('.top-actions { width: 100%', $css);self::assertStringContainsString('@media (max-width: 900px)',$css);self::assertStringContainsString('grid-auto-rows: minmax(44px, auto)',$css);self::assertStringContainsString('.phase11-table-wrap',$css);self::assertStringContainsString('margin: 0 38px',$css);self::assertStringContainsString("./app.js?v=12.0.2",$phase3);self::assertStringContainsString("./app.js?v=12.0.2",$phase4);self::assertStringContainsString('assets/js/app.js?v=12.0.2',$page);}
 public function testPublicacionTieneVerificadorYDocumentosFinales():void{$root=dirname(__DIR__,2);$script=file_get_contents($root.'/scripts/release_check.php');foreach(['installed.lock','Content-Security-Policy','014_reports_audit_storage_cron','Cinco roles definitivos']as$value)self::assertStringContainsString($value,$script);self::assertFileExists($root.'/docs/manual-tecnico/despliegue-final.md');self::assertFileExists($root.'/docs/manual-usuario/manual-final-por-rol.md');self::assertFileExists($root.'/docs/checklist-fase12.md');}
 public function testMenusFinalesRespetanRolesBase():void{$config=require dirname(__DIR__,2).'/config/modules.php';$visible=static function(string$role)use($config):array{$permissions=$config['roles'][$role];return array_keys(array_filter($config['modules'],static fn(array$m):bool=>array_intersect($m['permissions'],$permissions)!==[]&&(!isset($m['roles'])||in_array($role,$m['roles'],true))));};self::assertContains('auditoria',$visible('admin'));self::assertNotContains('mantenimiento',$visible('admin'));self::assertContains('reportes',$visible('supervisor'));self::assertNotContains('reportes',$visible('guard'));self::assertSame(['mis_unidades','visitas','proveedores','reportes'],$visible('resident'));}
 public function testTablasOperativasYModoOscuroTienenContratoVisual():void{$root=dirname(__DIR__,2);$phase5=file_get_contents($root.'/public/assets/css/phase5.css');$phase12=file_get_contents($root.'/public/assets/css/phase12.css');self::assertStringContainsString('.phase5-workspace .data-table',$phase5);self::assertStringContainsString('var(--table-hover)',$phase12);self::assertStringContainsString('html[data-theme="dark"] .ghost-button',$phase12);self::assertStringContainsString('background: var(--surface-soft)',$phase12);}
 public function testCrudAdministrativoEsEditableReversibleYAuditable():void{$root=dirname(__DIR__,2);$routes=file_get_contents($root.'/routes/api.php');$organization=file_get_contents($root.'/app/Services/OrganizationService.php');$workforce=file_get_contents($root.'/app/Services/WorkforceService.php');$phase3=file_get_contents($root.'/public/assets/js/phase3.js');$phase4=file_get_contents($root.'/public/assets/js/phase4.js');foreach(['/organization/update','/workforce/update']as$route)self::assertStringContainsString($route,$routes);self::assertStringContainsString("['superadmin','admin']",$organization);self::assertStringContainsString(".'_updated'",$organization);self::assertStringContainsString('workforce.assignment_updated',$workforce);self::assertStringContainsString("'set_guard_active'",$workforce);self::assertStringContainsString("'set_shift_active'",$workforce);self::assertStringContainsString("'/organization/update'",$phase3);self::assertStringContainsString("'/workforce/update'",$phase4);self::assertStringContainsString("'Editar'",$phase3);self::assertStringContainsString("'Eliminar'",$phase4);}
}
