<?php
declare(strict_types=1);
namespace Vigilancia\Repositories;

use PDO;

final class EventRepository
{
    public function __construct(private PDO $pdo) {}

    public function types(bool $activeOnly=true):array{return$this->all('SELECT * FROM event_types'.($activeOnly?' WHERE is_active=1':'').' ORDER BY sort_order,name',[]);}
    public function type(int$id):?array{return$this->one('SELECT * FROM event_types WHERE id=?',[$id]);}
    public function saveType(array$d):int{if($d['id']){$this->pdo->prepare('UPDATE event_types SET name=?,sort_order=?,default_priority=?,evidence_required=?,is_active=?,updated_at=UTC_TIMESTAMP() WHERE id=?')->execute([$d['name'],$d['order'],$d['priority'],$d['required'],$d['active'],$d['id']]);return$d['id'];}$s=$this->pdo->prepare('INSERT INTO event_types(code,name,sort_order,default_priority,evidence_required,is_active,created_at,updated_at) VALUES(?,?,?,?,?,?,UTC_TIMESTAMP(),UTC_TIMESTAMP())');$s->execute([$d['code'],$d['name'],$d['order'],$d['priority'],$d['required'],$d['active']]);return(int)$this->pdo->lastInsertId();}
    public function createEvent(array$d):int{$s=$this->pdo->prepare("INSERT INTO events(event_type_id,operational_session_id,client_id,location_id,access_point_id,guard_user_id,description,priority,status,occurred_at,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?, 'submitted',UTC_TIMESTAMP(),?,UTC_TIMESTAMP(),UTC_TIMESTAMP())");$s->execute([$d['type_id'],$d['session_id']?:null,$d['client_id'],$d['location_id'],$d['point_id']?:null,$d['guard_id']?:null,$d['description'],$d['priority'],$d['created_by']]);return(int)$this->pdo->lastInsertId();}
    public function event(int$id):?array{return$this->one("SELECT e.*,et.code type_code,et.name type_name,et.evidence_required,u.full_name guard_name,c.name client_name,l.name location_name,ap.name access_point_name FROM events e JOIN event_types et ON et.id=e.event_type_id LEFT JOIN users u ON u.id=e.guard_user_id JOIN clients c ON c.id=e.client_id JOIN locations l ON l.id=e.location_id LEFT JOIN access_points ap ON ap.id=e.access_point_id WHERE e.id=?",[$id]);}
    public function listEvents(array$actor):array{$sql="SELECT e.id,et.name type_name,e.description,e.priority,e.status,e.occurred_at,e.cancelled_at,e.cancellation_reason,u.full_name guard_name,c.name client_name,l.name location_name,ap.name access_point_name,(SELECT COUNT(*) FROM event_evidence ee WHERE ee.event_id=e.id) evidence_count,(SELECT COUNT(*) FROM event_comments ec WHERE ec.event_id=e.id) comment_count FROM events e JOIN event_types et ON et.id=e.event_type_id LEFT JOIN users u ON u.id=e.guard_user_id JOIN clients c ON c.id=e.client_id JOIN locations l ON l.id=e.location_id LEFT JOIN access_points ap ON ap.id=e.access_point_id WHERE 1=1";$p=[];if($actor['role_code']==='admin'){$sql.=' AND c.surveillance_company_id=?';$p[]=$actor['surveillance_company_id'];}elseif($actor['role_code']==='supervisor'){$sql.=' AND EXISTS(SELECT 1 FROM user_location_scopes s WHERE s.user_id=? AND s.location_id=e.location_id AND s.is_active=1)';$p[]=$actor['id'];}elseif($actor['role_code']==='guard'){$sql.=' AND e.guard_user_id=?';$p[]=$actor['id'];}$sql.=' ORDER BY e.occurred_at DESC LIMIT 250';return$this->all($sql,$p);}
    public function inScope(array$actor,array$event):bool{if($actor['role_code']==='superadmin')return true;if($actor['role_code']==='admin'){return(int)$actor['surveillance_company_id']===(int)$this->value('SELECT surveillance_company_id FROM clients WHERE id=?',[$event['client_id']]);}if($actor['role_code']==='supervisor')return(bool)$this->value('SELECT COUNT(*) FROM user_location_scopes WHERE user_id=? AND location_id=? AND is_active=1',[$actor['id'],$event['location_id']]);return$actor['role_code']==='guard'&&(int)$event['guard_user_id']===(int)$actor['id'];}
    public function comments(int$id):array{return$this->all('SELECT ec.id,ec.comment,ec.created_at,u.full_name author_name FROM event_comments ec JOIN users u ON u.id=ec.author_user_id WHERE ec.event_id=? ORDER BY ec.created_at',[$id]);}
    public function addComment(int$id,int$user,string$comment):void{$this->pdo->prepare('INSERT INTO event_comments(event_id,author_user_id,comment,created_at) VALUES(?,?,?,UTC_TIMESTAMP())')->execute([$id,$user,$comment]);}
    public function cancel(int$id,int$user,string$reason):void{$this->pdo->prepare("UPDATE events SET status='cancelled',cancelled_by=?,cancellation_reason=?,cancelled_at=UTC_TIMESTAMP(),updated_at=UTC_TIMESTAMP() WHERE id=? AND status='submitted'")->execute([$user,$reason,$id]);}
    public function evidenceTotals(int$id):array{$s=$this->pdo->prepare('SELECT COUNT(*) files,COALESCE(SUM(file_size),0) bytes FROM event_evidence WHERE event_id=?');$s->execute([$id]);return$s->fetch();}
    public function addEvidence(array$d):int{$s=$this->pdo->prepare('INSERT INTO event_evidence(event_id,uploaded_by,media_type,mime_type,file_path,file_size,duration_seconds,watermark_text,captured_at,created_at) VALUES(?,?,?,?,?,?,?,?,UTC_TIMESTAMP(),UTC_TIMESTAMP())');$s->execute([$d['event_id'],$d['user_id'],$d['media_type'],$d['mime'],$d['path'],$d['size'],$d['duration'],$d['watermark']]);return(int)$this->pdo->lastInsertId();}
    public function evidence(int$id):?array{return$this->one('SELECT ee.*,e.location_id,e.guard_user_id FROM event_evidence ee JOIN events e ON e.id=ee.event_id WHERE ee.id=?',[$id]);}
    public function evidenceForEvent(int$id):array{return$this->all('SELECT id,media_type,mime_type,file_size,duration_seconds,watermark_text,captured_at FROM event_evidence WHERE event_id=? ORDER BY captured_at',[$id]);}

    public function expireRounds():void{$this->pdo->exec("UPDATE rounds r JOIN round_policies rp ON rp.location_id=r.location_id SET r.status='incomplete',r.updated_at=UTC_TIMESTAMP() WHERE r.status='open' AND TIMESTAMPDIFF(MINUTE,r.started_at,UTC_TIMESTAMP())>rp.max_duration_minutes");}
    public function openRound(int$guard):?array{$this->expireRounds();return$this->one("SELECT r.*,e.description,(SELECT COUNT(*) FROM event_evidence ee WHERE ee.event_id=r.event_id) evidence_count FROM rounds r JOIN events e ON e.id=r.event_id WHERE r.guard_user_id=? AND r.status='open' ORDER BY r.id DESC LIMIT 1",[$guard]);}
    public function createRound(array$d):int{$s=$this->pdo->prepare("INSERT INTO rounds(event_id,operational_session_id,client_id,location_id,access_point_id,guard_user_id,round_kind,status,started_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,'open',UTC_TIMESTAMP(),UTC_TIMESTAMP(),UTC_TIMESTAMP())");$s->execute([$d['event_id'],$d['session_id'],$d['client_id'],$d['location_id'],$d['point_id'],$d['guard_id'],$d['kind']]);return(int)$this->pdo->lastInsertId();}
    public function round(int$id):?array{return$this->one("SELECT r.*,e.description,e.priority,u.full_name guard_name,c.name client_name,l.name location_name,ap.name access_point_name,(SELECT COUNT(*) FROM event_evidence ee WHERE ee.event_id=r.event_id) evidence_count FROM rounds r JOIN events e ON e.id=r.event_id JOIN users u ON u.id=r.guard_user_id JOIN clients c ON c.id=r.client_id JOIN locations l ON l.id=r.location_id JOIN access_points ap ON ap.id=r.access_point_id WHERE r.id=?",[$id]);}
    public function listRounds(array$actor):array{$this->expireRounds();$sql="SELECT r.id,r.event_id,r.round_kind,r.status,r.started_at,r.ended_at,r.observations,r.supervisor_comment,u.full_name guard_name,c.name client_name,l.name location_name,ap.name access_point_name,(SELECT COUNT(*) FROM event_evidence ee WHERE ee.event_id=r.event_id) evidence_count FROM rounds r JOIN users u ON u.id=r.guard_user_id JOIN clients c ON c.id=r.client_id JOIN locations l ON l.id=r.location_id JOIN access_points ap ON ap.id=r.access_point_id WHERE 1=1";$p=[];if($actor['role_code']==='admin'){$sql.=' AND c.surveillance_company_id=?';$p[]=$actor['surveillance_company_id'];}elseif($actor['role_code']==='supervisor'){$sql.=' AND EXISTS(SELECT 1 FROM user_location_scopes s WHERE s.user_id=? AND s.location_id=r.location_id AND s.is_active=1)';$p[]=$actor['id'];}elseif($actor['role_code']==='guard'){$sql.=' AND r.guard_user_id=?';$p[]=$actor['id'];}$sql.=' ORDER BY r.started_at DESC LIMIT 250';return$this->all($sql,$p);}
    public function finishRound(int$id,string$observations):void{$this->pdo->prepare("UPDATE rounds SET status='completed',ended_at=UTC_TIMESTAMP(),observations=?,updated_at=UTC_TIMESTAMP() WHERE id=? AND status='open'")->execute([$observations,$id]);}
    public function supervisorCloseRound(int$id,int$user,string$comment):void{$this->pdo->prepare("UPDATE rounds SET status='supervisor_closed',ended_at=COALESCE(ended_at,UTC_TIMESTAMP()),closed_by=?,supervisor_comment=?,updated_at=UTC_TIMESTAMP() WHERE id=? AND status IN ('open','incomplete')")->execute([$user,$comment,$id]);}
    public function policy(int$location):array{return$this->one('SELECT * FROM round_policies WHERE location_id=?',[$location])?:['max_duration_minutes'=>60,'minimum_per_shift'=>1];}

    public function noveltyForSession(int$session):?array{return$this->one('SELECT * FROM shift_novelties WHERE operational_session_id=?',[$session]);}
    public function createNovelty(array$d):int{$s=$this->pdo->prepare('INSERT INTO shift_novelties(operational_session_id,event_id,guard_user_id,client_id,location_id,access_point_id,novelty_status,description,created_at) VALUES(?,?,?,?,?,?,?,?,UTC_TIMESTAMP())');$s->execute([$d['session_id'],$d['event_id'],$d['guard_id'],$d['client_id'],$d['location_id'],$d['point_id'],$d['status'],$d['description']]);return(int)$this->pdo->lastInsertId();}
    public function previousNovelties(int$location,int$point,int$session):array{return$this->all('SELECT sn.id,sn.novelty_status,sn.description,sn.created_at,u.full_name guard_name,e.id event_id,(SELECT COUNT(*) FROM event_comments ec WHERE ec.event_id=e.id) comment_count FROM shift_novelties sn JOIN users u ON u.id=sn.guard_user_id JOIN events e ON e.id=sn.event_id WHERE sn.location_id=? AND sn.access_point_id=? AND sn.operational_session_id<>? ORDER BY sn.created_at DESC LIMIT 10',[$location,$point,$session]);}
    private function one(string$sql,array$p):?array{$s=$this->pdo->prepare($sql);$s->execute($p);return$s->fetch()?:null;}private function all(string$sql,array$p):array{$s=$this->pdo->prepare($sql);$s->execute($p);return$s->fetchAll();}private function value(string$sql,array$p):mixed{$s=$this->pdo->prepare($sql);$s->execute($p);return$s->fetchColumn();}
}
