<?php
declare(strict_types=1);
namespace Vigilancia\Repositories;
use PDO;

final class MaintenanceRepository
{
    public function __construct(private PDO $pdo){}
    public function lock():bool{return (int)$this->pdo->query("SELECT GET_LOCK('vigilancia_phase11_cron',0)")->fetchColumn()===1;}
    public function unlock():void{$this->pdo->query("SELECT RELEASE_LOCK('vigilancia_phase11_cron')");}
    public function start(string $task):int{$s=$this->pdo->prepare("INSERT INTO cron_runs(task_name,status,started_at) VALUES(?,'running',UTC_TIMESTAMP())");$s->execute([$task]);return(int)$this->pdo->lastInsertId();}
    public function finish(int$id,string$status,array$result,?string$error,int$ms):void{$s=$this->pdo->prepare("UPDATE cron_runs SET status=?,finished_at=UTC_TIMESTAMP(),duration_ms=?,result_json=?,error_message=?,next_expected_at=DATE_ADD(UTC_TIMESTAMP(),INTERVAL 5 MINUTE) WHERE id=?");$s->execute([$status,$ms,json_encode($result,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR),$error,$id]);}
    public function latest():array{return$this->all("SELECT cr.* FROM cron_runs cr JOIN (SELECT task_name,MAX(id) id FROM cron_runs GROUP BY task_name)x ON x.id=cr.id ORDER BY cr.task_name",[]);}
    public function setting(string$key,int$default):int{$s=$this->pdo->prepare('SELECT setting_value FROM system_settings WHERE setting_key=?');$s->execute([$key]);$v=$s->fetchColumn();return$v===false?$default:(int)$v;}
    public function absenceCandidates(string$date):array{$sql="SELECT ga.*,s.start_time,s.end_time FROM guard_assignments ga JOIN shifts s ON s.id=ga.shift_id WHERE ga.status='active' AND ga.start_date<=? AND (ga.end_date IS NULL OR ga.end_date>=?) AND NOT EXISTS(SELECT 1 FROM attendance_records ar WHERE ar.assignment_id=ga.id AND DATE(ar.scheduled_start_at)=?)";return$this->all($sql,[$date,$date,$date]);}
    public function addAbsence(array$r,string$date,string$start,string$end):bool{$s=$this->pdo->prepare("INSERT IGNORE INTO attendance_absences(assignment_id,guard_user_id,shift_id,client_id,location_id,access_point_id,absence_date,scheduled_start_at,scheduled_end_at,detected_at) VALUES(?,?,?,?,?,?,?,?,?,UTC_TIMESTAMP())");$s->execute([$r['id'],$r['guard_user_id'],$r['shift_id'],$r['client_id'],$r['location_id'],$r['access_point_id'],$date,$start,$end]);return$s->rowCount()>0;}
    public function closeIncompleteRounds():int{$s=$this->pdo->prepare("UPDATE rounds r JOIN round_policies rp ON rp.location_id=r.location_id SET r.status='incomplete',r.ended_at=UTC_TIMESTAMP(),r.updated_at=UTC_TIMESTAMP() WHERE r.status='open' AND r.started_at<DATE_SUB(UTC_TIMESTAMP(),INTERVAL rp.max_duration_minutes MINUTE)");$s->execute();return$s->rowCount();}
    public function expireQr():int{$count=0;foreach(["UPDATE visitor_passes SET status='expired',updated_at=UTC_TIMESTAMP() WHERE status='pending' AND valid_until<UTC_TIMESTAMP()","UPDATE guard_credentials SET status='expired' WHERE status='active' AND expires_at IS NOT NULL AND expires_at<UTC_TIMESTAMP()"]as$sql){$s=$this->pdo->prepare($sql);$s->execute();$count+=$s->rowCount();}return$count;}
    public function pendingSupervisions():int{return(int)$this->pdo->query("SELECT COUNT(*) FROM supervision_schedules WHERE status='pending' AND scheduled_at<UTC_TIMESTAMP()")->fetchColumn();}
    public function storage():array{$sql="SELECT c.id client_id,c.name,10737418240 limit_bytes,COALESCE(ev.bytes,0)+COALESCE(se.bytes,0) usage_bytes FROM clients c LEFT JOIN(SELECT e.client_id,SUM(ee.file_size) bytes FROM event_evidence ee JOIN events e ON e.id=ee.event_id GROUP BY e.client_id)ev ON ev.client_id=c.id LEFT JOIN(SELECT s.client_id,SUM(x.file_size)bytes FROM supervision_evidence x JOIN supervisions s ON s.id=x.supervision_id GROUP BY s.client_id)se ON se.client_id=c.id ORDER BY c.name";return$this->all($sql,[]);}
    public function alertStorage(int$threshold):int{$count=0;foreach($this->storage()as$row){$usage=(int)$row['usage_bytes'];$limit=(int)$row['limit_bytes'];if($limit<1||$usage/$limit*100<$threshold)continue;$s=$this->pdo->prepare("INSERT INTO storage_alerts(client_id,usage_bytes,limit_bytes,threshold_percent,status,notified_at) SELECT ?,?,?,?,'notified',UTC_TIMESTAMP() WHERE NOT EXISTS(SELECT 1 FROM storage_alerts WHERE client_id=? AND status='notified' AND notified_at>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 1 DAY))");$s->execute([$row['client_id'],$usage,$limit,$threshold,$row['client_id']]);if($s->rowCount()){ $count++;$n=$this->pdo->prepare("INSERT IGNORE INTO notifications(user_id,notification_type,title,message,priority,related_type,related_id,related_view,deduplication_key,created_at,expires_at) SELECT u.id,'storage_alert','Almacenamiento cerca del límite',CONCAT(?,' alcanzó el ',?,'% de su cuota.'),'important','client',?,'mantenimiento',SHA2(CONCAT('storage-',?,'-',UTC_DATE()),256),UTC_TIMESTAMP(),DATE_ADD(UTC_TIMESTAMP(),INTERVAL 12 MONTH) FROM users u JOIN roles r ON r.id=u.role_id JOIN clients c ON c.surveillance_company_id=u.surveillance_company_id WHERE c.id=? AND r.code IN ('superadmin','admin') AND u.is_active=1");$n->execute([$row['name'],$threshold,$row['client_id'],$row['client_id'],$row['client_id']]);}}return$count;}
    public function retentionCandidates(int$months,int$days,int$warning):array{$evidenceCutoff=gmdate('Y-m-d H:i:s',strtotime("-$months months +$warning days"));$identificationCutoff=gmdate('Y-m-d H:i:s',strtotime("-$days days +$warning days"));$sql="SELECT e.client_id,'event_evidence' asset_type,ee.id record_id,ee.file_path,DATE_ADD(ee.captured_at,INTERVAL $months MONTH) delete_at FROM event_evidence ee JOIN events e ON e.id=ee.event_id WHERE ee.captured_at<? UNION ALL SELECT l.client_id,'visitor_identification',va.id,va.identification_photo_path,DATE_ADD(va.created_at,INTERVAL $days DAY) FROM visitor_accesses va JOIN visitor_passes vp ON vp.id=va.visitor_pass_id JOIN locations l ON l.id=vp.location_id WHERE va.identification_photo_path IS NOT NULL AND va.created_at<?";$s=$this->pdo->prepare($sql);$s->execute([$evidenceCutoff,$identificationCutoff]);return$s->fetchAll();}
    public function scheduleRetention(array$r):bool{$s=$this->pdo->prepare("INSERT IGNORE INTO retention_actions(client_id,asset_type,record_id,file_path,scheduled_delete_at,notified_at) VALUES(?,?,?,?,?,UTC_TIMESTAMP())");$s->execute([$r['client_id'],$r['asset_type'],$r['record_id'],$r['file_path'],$r['delete_at']]);if(!$s->rowCount())return false;$id=(int)$this->pdo->lastInsertId();$n=$this->pdo->prepare("INSERT IGNORE INTO notifications(user_id,notification_type,title,message,priority,related_type,related_id,related_view,deduplication_key,created_at,expires_at) SELECT u.id,'retention_warning','Evidencia próxima a eliminar',CONCAT('El archivo ',?,' se eliminará el ',?,' conforme a retención.'),'important','retention_action',?,'mantenimiento',SHA2(CONCAT('retention-',?,'-',u.id),256),UTC_TIMESTAMP(),DATE_ADD(UTC_TIMESTAMP(),INTERVAL 12 MONTH) FROM users u JOIN roles ro ON ro.id=u.role_id JOIN clients c ON c.surveillance_company_id=u.surveillance_company_id WHERE c.id=? AND ro.code IN ('superadmin','admin') AND u.is_active=1");$n->execute([$r['asset_type'],$r['delete_at'],$id,$id,$r['client_id']]);return true;}
    public function dueRetention():array{return$this->all("SELECT * FROM retention_actions WHERE status='notified' AND scheduled_delete_at<=UTC_TIMESTAMP()",[]);}
    public function deletedRetention(int$id):void{$this->pdo->prepare("UPDATE retention_actions SET status='deleted',deleted_at=UTC_TIMESTAMP() WHERE id=?")->execute([$id]);$this->pdo->prepare("INSERT INTO security_logs(user_id,event_type,module_name,record_type,record_id,ip_address,user_agent,context_json,occurred_at) VALUES(NULL,'retention.deleted','retention','retention_action',?,'127.0.0.1','cron',JSON_OBJECT('retention_action_id',?),UTC_TIMESTAMP())")->execute([$id,$id]);}
    private function all(string$q,array$p):array{$s=$this->pdo->prepare($q);$s->execute($p);return$s->fetchAll();}
}
