<?php
declare(strict_types=1);namespace Vigilancia\Repositories;use PDO;
final class OfflineRepository{public function __construct(private PDO$pdo){}
 public function authorize(int$guard,string$device,string$token):array{$s=$this->pdo->prepare("INSERT INTO offline_devices(guard_user_id,device_identifier,sync_token_hash,status,authorized_at,expires_at,created_at,updated_at) VALUES(?,?,?,'active',UTC_TIMESTAMP(),DATE_ADD(UTC_TIMESTAMP(),INTERVAL 24 HOUR),UTC_TIMESTAMP(),UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE sync_token_hash=VALUES(sync_token_hash),status='active',authorized_at=UTC_TIMESTAMP(),expires_at=DATE_ADD(UTC_TIMESTAMP(),INTERVAL 24 HOUR),revoked_at=NULL,updated_at=UTC_TIMESTAMP()");$s->execute([$guard,$device,$token]);return$this->deviceByToken($token)??[];}
 public function deviceByToken(string$hash):?array{$s=$this->pdo->prepare("SELECT * FROM offline_devices WHERE sync_token_hash=? AND status='active' AND revoked_at IS NULL AND expires_at>UTC_TIMESTAMP() LIMIT 1");$s->execute([$hash]);return$s->fetch()?:null;}
 public function existing(string$uuid):?array{return$this->one('SELECT * FROM offline_operations WHERE client_uuid=?',[$uuid]);}
 public function conflict(string$key):?array{return$this->one("SELECT * FROM offline_operations WHERE entity_key=? AND status IN ('synchronized','conflict','accepted','expired') ORDER BY id DESC LIMIT 1",[$key]);}
 public function markConflict(int$id,string$group):void{$this->pdo->prepare("UPDATE offline_operations SET status='conflict',conflict_group=?,updated_at=UTC_TIMESTAMP() WHERE id=? AND status NOT IN ('accepted','rejected')")->execute([$group,$id]);}
 public function insert(array$d):int{$s=$this->pdo->prepare("INSERT INTO offline_operations(client_uuid,offline_device_id,guard_user_id,operational_session_id,client_id,location_id,access_point_id,operation_type,entity_key,payload_json,evidence_path,occurred_at,received_at,expires_at,status,conflict_group,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,UTC_TIMESTAMP(),DATE_ADD(?,INTERVAL 12 HOUR),?,?,UTC_TIMESTAMP(),UTC_TIMESTAMP())");$s->execute([$d['uuid'],$d['device_id'],$d['guard_id'],$d['session_id']?:null,$d['client_id']?:null,$d['location_id']?:null,$d['point_id']?:null,$d['type'],$d['entity_key']?:null,json_encode($d['payload'],JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR),$d['evidence'],$d['occurred_at'],$d['occurred_at'],$d['status'],$d['conflict_group']]);return(int)$this->pdo->lastInsertId();}
 public function touchDevice(int$id):void{$this->pdo->prepare('UPDATE offline_devices SET last_sync_at=UTC_TIMESTAMP(),updated_at=UTC_TIMESTAMP() WHERE id=?')->execute([$id]);}
 public function reviewable(array$actor):array{$sql="SELECT oo.id,oo.client_uuid,oo.operation_type,oo.entity_key,oo.payload_json,oo.occurred_at,oo.received_at,oo.expires_at,oo.status,oo.conflict_group,u.full_name guard_name,l.name location_name,ap.name access_point_name FROM offline_operations oo JOIN users u ON u.id=oo.guard_user_id LEFT JOIN locations l ON l.id=oo.location_id LEFT JOIN access_points ap ON ap.id=oo.access_point_id WHERE oo.status IN ('conflict','expired') AND u.surveillance_company_id=?";$p=[$actor['surveillance_company_id']];if($actor['role_code']==='supervisor'){$sql.=" AND EXISTS(SELECT 1 FROM user_location_scopes s WHERE s.user_id=? AND s.location_id=oo.location_id AND s.is_active=1)";$p[]=$actor['id'];}$sql.=' ORDER BY oo.received_at DESC';return$this->all($sql,$p);}
 public function scopedReviewable(int$id,array$actor):?array{$sql="SELECT oo.* FROM offline_operations oo JOIN users u ON u.id=oo.guard_user_id WHERE oo.id=? AND oo.status IN ('conflict','expired') AND u.surveillance_company_id=?";$p=[$id,$actor['surveillance_company_id']];if($actor['role_code']==='supervisor'){$sql.=" AND EXISTS(SELECT 1 FROM user_location_scopes s WHERE s.user_id=? AND s.location_id=oo.location_id AND s.is_active=1)";$p[]=$actor['id'];}return$this->one($sql,$p);}
 public function inScope(int$id,array$actor):bool{return$this->scopedReviewable($id,$actor)!==null;}
 public function review(int$id,string$status,int$actor,string$comment):void{$this->pdo->prepare('UPDATE offline_operations SET status=?,reviewed_by=?,review_comment=?,reviewed_at=UTC_TIMESTAMP(),updated_at=UTC_TIMESTAMP() WHERE id=?')->execute([$status,$actor,$comment,$id]);}
 private function one(string$q,array$p):?array{$s=$this->pdo->prepare($q);$s->execute($p);return$s->fetch()?:null;}private function all(string$q,array$p):array{$s=$this->pdo->prepare($q);$s->execute($p);return$s->fetchAll();}}
