<?php
declare(strict_types=1);
namespace Vigilancia\Repositories;

use PDO;

final class OperationalRepository
{
    public function __construct(private PDO $pdo){}
    public function catalog():array{return $this->fetch("SELECT c.id client_id,c.name client_name,l.id location_id,l.name location_name,ap.id access_point_id,ap.name access_point_name FROM access_points ap JOIN locations l ON l.id=ap.location_id JOIN clients c ON c.id=l.client_id WHERE ap.is_active=1 AND l.is_active=1 AND c.is_active=1 ORDER BY c.name,l.name,ap.name",[]);}
    public function credential(string $hash):?array{$s=$this->pdo->prepare("SELECT gc.id credential_id,gc.guard_user_id,gc.token_hash,gc.expires_at,u.full_name,u.surveillance_company_id,u.is_active,gp.pin_hash,gp.pin_failed_attempts,gp.pin_blocked_until,gp.status guard_status FROM guard_credentials gc JOIN users u ON u.id=gc.guard_user_id JOIN roles r ON r.id=u.role_id AND r.code='guard' JOIN guard_profiles gp ON gp.user_id=u.id WHERE gc.token_hash=? AND gc.status='active' AND (gc.expires_at IS NULL OR gc.expires_at>UTC_TIMESTAMP()) LIMIT 1");$s->execute([$hash]);return$s->fetch()?:null;}
    public function credentialByReference(string $reference):?array{$s=$this->pdo->prepare("SELECT gc.id credential_id,gc.guard_user_id,gc.token_hash,gc.expires_at,u.full_name,u.surveillance_company_id,u.is_active,gp.pin_hash,gp.pin_failed_attempts,gp.pin_blocked_until,gp.status guard_status FROM guard_credentials gc JOIN users u ON u.id=gc.guard_user_id JOIN roles r ON r.id=u.role_id AND r.code='guard' JOIN guard_profiles gp ON gp.user_id=u.id WHERE gc.token_reference=? AND gc.status='active' AND (gc.expires_at IS NULL OR gc.expires_at>UTC_TIMESTAMP()) LIMIT 2");$s->execute([$reference]);$rows=$s->fetchAll();return count($rows)===1?$rows[0]:null;}
    public function failedPin(int $guardId,int $attempts,?string $blocked):void{$this->pdo->prepare('UPDATE guard_profiles SET pin_failed_attempts=?,pin_blocked_until=?,updated_at=UTC_TIMESTAMP() WHERE user_id=?')->execute([$attempts,$blocked,$guardId]);}
    public function resetPinFailures(int $guardId):void{$this->pdo->prepare('UPDATE guard_profiles SET pin_failed_attempts=0,pin_blocked_until=NULL,updated_at=UTC_TIMESTAMP() WHERE user_id=?')->execute([$guardId]);}
    public function assignments(int $guardId,int $clientId,int $locationId,int $pointId):array{return$this->fetch("SELECT ga.*,s.name shift_name,s.start_time,s.end_time,s.crosses_midnight,s.tolerance_minutes,s.early_departure_tolerance_minutes,s.overtime_after_minutes FROM guard_assignments ga JOIN shifts s ON s.id=ga.shift_id AND s.is_active=1 WHERE ga.guard_user_id=? AND ga.client_id=? AND ga.location_id=? AND ga.access_point_id=? AND ga.status='active' ORDER BY ga.id DESC",[$guardId,$clientId,$locationId,$pointId]);}
    public function activeForGuard(int $id,bool $lock=false):?array{return$this->one("SELECT * FROM operational_sessions WHERE guard_user_id=? AND status='active' ORDER BY id DESC LIMIT 1".($lock?' FOR UPDATE':''),[$id]);}
    public function activeForPoint(int $id,bool $lock=false):?array{return$this->one("SELECT * FROM operational_sessions WHERE access_point_id=? AND status='active' ORDER BY id DESC LIMIT 1".($lock?' FOR UPDATE':''),[$id]);}
    public function create(array $d):int{$s=$this->pdo->prepare("INSERT INTO operational_sessions(guard_user_id,assignment_id,shift_id,client_id,location_id,access_point_id,status,started_at,entry_photo_path,entry_classification,device_type,browser_name,operating_system,ip_address,device_identifier,connection_status,created_at,updated_at) VALUES(?,?,?,?,?,?,'active',?,?,?,?,?,?,?,?,?,UTC_TIMESTAMP(),UTC_TIMESTAMP())");$s->execute([$d['guard_user_id'],$d['assignment_id'],$d['shift_id'],$d['client_id'],$d['location_id'],$d['access_point_id'],$d['now_utc'],$d['photo'],$d['entry_classification'],$d['device_type'],$d['browser'],$d['os'],$d['ip'],$d['device_identifier'],$d['connection']]);$id=(int)$this->pdo->lastInsertId();$s=$this->pdo->prepare("INSERT INTO attendance_records(operational_session_id,guard_user_id,assignment_id,shift_id,client_id,location_id,access_point_id,scheduled_start_at,scheduled_end_at,actual_entry_at,entry_classification,minutes_late,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?, 'open',UTC_TIMESTAMP(),UTC_TIMESTAMP())");$s->execute([$id,$d['guard_user_id'],$d['assignment_id'],$d['shift_id'],$d['client_id'],$d['location_id'],$d['access_point_id'],$d['scheduled_start'],$d['scheduled_end'],$d['now_utc'],$d['entry_classification'],$d['minutes_late']]);return$id;}
    public function session(int $id):?array{return$this->one("SELECT os.*,u.full_name,c.name client_name,l.name location_name,ap.name access_point_name,s.name shift_name,ar.scheduled_start_at,ar.scheduled_end_at,s.early_departure_tolerance_minutes,s.overtime_after_minutes FROM operational_sessions os JOIN users u ON u.id=os.guard_user_id JOIN clients c ON c.id=os.client_id JOIN locations l ON l.id=os.location_id JOIN access_points ap ON ap.id=os.access_point_id JOIN shifts s ON s.id=os.shift_id JOIN attendance_records ar ON ar.operational_session_id=os.id WHERE os.id=?",[$id]);}
    public function close(int $id,string $now,string $classification,int $early,int $overtime,string $method,?int $actor,?string $comment,string $status='closed'):void{$this->pdo->prepare("UPDATE operational_sessions SET status=?,ended_at=?,exit_classification=?,close_method=?,closed_by=?,close_comment=?,updated_at=UTC_TIMESTAMP() WHERE id=? AND status='active'")->execute([$status,$now,$classification,$method,$actor,$comment,$id]);$att=$status==='manual_closed'?'incomplete':'complete';$this->pdo->prepare("UPDATE attendance_records SET actual_exit_at=?,exit_classification=?,minutes_early=?,overtime_minutes=?,status=?,updated_at=UTC_TIMESTAMP() WHERE operational_session_id=?")->execute([$now,$classification,$early,$overtime,$att,$id]);}
    public function list(array $actor,bool $attendance=false):array{$table=$attendance?'attendance_records ar JOIN operational_sessions os ON os.id=ar.operational_session_id':'operational_sessions os LEFT JOIN attendance_records ar ON ar.operational_session_id=os.id';$sql="SELECT os.id,os.guard_user_id,u.full_name guard_name,c.name client_name,l.name location_name,ap.name access_point_name,s.name shift_name,os.status,os.started_at,os.ended_at,os.entry_classification,os.exit_classification,ar.minutes_late,ar.minutes_early,ar.overtime_minutes".($attendance?',ar.scheduled_start_at,ar.scheduled_end_at,ar.status attendance_status':'')." FROM $table JOIN users u ON u.id=os.guard_user_id JOIN clients c ON c.id=os.client_id JOIN locations l ON l.id=os.location_id JOIN access_points ap ON ap.id=os.access_point_id JOIN shifts s ON s.id=os.shift_id WHERE u.surveillance_company_id=?";$p=[$actor['surveillance_company_id']];if($actor['role_code']==='supervisor'){$sql.=" AND EXISTS(SELECT 1 FROM user_location_scopes us WHERE us.user_id=? AND us.location_id=os.location_id AND us.is_active=1)";$p[]=$actor['id'];}elseif($actor['role_code']==='guard'){$sql.=' AND os.guard_user_id=?';$p[]=$actor['id'];}$sql.=' ORDER BY os.started_at DESC LIMIT 200';return$this->fetch($sql,$p);}
    public function inScope(int $sessionId,array $actor):bool{$row=$this->session($sessionId);if(!$row||$row['status']!=='active')return false;if(in_array($actor['role_code'],['superadmin'],true))return true;if($actor['role_code']==='admin'&&(int)$actor['surveillance_company_id']>0){$s=$this->pdo->prepare('SELECT surveillance_company_id FROM users WHERE id=?');$s->execute([$row['guard_user_id']]);return(int)$s->fetchColumn()===(int)$actor['surveillance_company_id'];}if($actor['role_code']==='supervisor'){$s=$this->pdo->prepare('SELECT COUNT(*) FROM user_location_scopes WHERE user_id=? AND location_id=? AND is_active=1');$s->execute([$actor['id'],$row['location_id']]);return(int)$s->fetchColumn()>0;}return false;}
    private function one(string$sql,array$p):?array{$s=$this->pdo->prepare($sql);$s->execute($p);return$s->fetch()?:null;}private function fetch(string$sql,array$p):array{$s=$this->pdo->prepare($sql);$s->execute($p);return$s->fetchAll();}
}
