<?php
declare(strict_types=1);
namespace Vigilancia\Repositories;
use PDO;
final class ReportRepository
{
 public function __construct(private PDO$pdo){}
 public function catalog(array$a):array{$locations=$this->locations($a);$ids=array_map('intval',array_column($locations,'id'));$clients=[];foreach($locations as$l)$clients[(int)$l['client_id']]=['id'=>(int)$l['client_id'],'name'=>$l['client_name']];if(!$ids)return['clients'=>[],'locations'=>[],'points'=>[],'guards'=>[],'shifts'=>[]];$m=implode(',',array_fill(0,count($ids),'?'));return['clients'=>array_values($clients),'locations'=>$locations,'points'=>$this->all("SELECT id,location_id,name FROM access_points WHERE location_id IN ($m) ORDER BY name",$ids),'guards'=>$this->all("SELECT DISTINCT u.id,u.full_name FROM guard_assignments ga JOIN users u ON u.id=ga.guard_user_id WHERE ga.location_id IN ($m) ORDER BY u.full_name",$ids),'shifts'=>$this->all('SELECT id,name FROM shifts WHERE surveillance_company_id=? ORDER BY name',[$a['surveillance_company_id']])];}
 public function create(string$folio,string$type,array$filters,int$user):int{$s=$this->pdo->prepare("INSERT INTO report_generations(folio,report_type,filters_json,generated_by,status,generated_at) VALUES(?,?,?,?, 'ready',UTC_TIMESTAMP())");$s->execute([$folio,$type,json_encode($filters,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR),$user]);return(int)$this->pdo->lastInsertId();}
 public function reports(array$a):array{$sql="SELECT rg.id,rg.folio,rg.report_type,rg.filters_json,rg.generated_at,u.full_name generated_by_name FROM report_generations rg JOIN users u ON u.id=rg.generated_by WHERE u.surveillance_company_id=?";$p=[$a['surveillance_company_id']];if($a['role_code']==='resident'){$sql.=' AND rg.generated_by=?';$p[]=$a['id'];}return$this->all($sql.' ORDER BY rg.generated_at DESC LIMIT 100',$p);}
 public function report(array$a,int$id):?array{$sql="SELECT rg.*,u.full_name generated_by_name,u.surveillance_company_id FROM report_generations rg JOIN users u ON u.id=rg.generated_by WHERE rg.id=? AND u.surveillance_company_id=?";$p=[$id,$a['surveillance_company_id']];if($a['role_code']==='resident'){$sql.=' AND rg.generated_by=?';$p[]=$a['id'];}return$this->one($sql,$p);}
 public function data(array$a,string$type,array$f):array{$ids=$this->filteredLocations($a,$f);if(!$ids)return[];$m=implode(',',array_fill(0,count($ids),'?'));$from=$f['date_from'].' 00:00:00';$to=$f['date_to'].' 23:59:59';$guard=(int)($f['guard_id']??0);$shift=(int)($f['shift_id']??0);$point=(int)($f['access_point_id']??0);$extra='';$tail=[];if($guard){$extra.=' AND x.guard_user_id=?';$tail[]=$guard;}if($shift){$extra.=' AND x.shift_id=?';$tail[]=$shift;}if($point){$extra.=' AND x.access_point_id=?';$tail[]=$point;}$base=array_merge($ids,[$from,$to],$tail);
  if(in_array($type,['attendance','late','worked_hours'],true)){$condition=$type==='late'?" AND x.entry_classification='late'":'';return$this->all("SELECT x.id,u.full_name vigilante,c.name cliente,l.name lugar,ap.name punto,s.name turno,x.actual_entry_at entrada,x.actual_exit_at salida,x.entry_classification clasificacion,x.minutes_late minutos_retardo,x.overtime_minutes minutos_extra,ROUND(TIMESTAMPDIFF(MINUTE,x.actual_entry_at,COALESCE(x.actual_exit_at,UTC_TIMESTAMP()))/60,2) horas FROM attendance_records x JOIN users u ON u.id=x.guard_user_id JOIN clients c ON c.id=x.client_id JOIN locations l ON l.id=x.location_id JOIN access_points ap ON ap.id=x.access_point_id JOIN shifts s ON s.id=x.shift_id WHERE x.location_id IN ($m) AND x.actual_entry_at BETWEEN ? AND ?$condition$extra ORDER BY x.actual_entry_at DESC LIMIT 5000",$base);}
  if($type==='absences')return$this->all("SELECT x.id,u.full_name vigilante,c.name cliente,l.name lugar,ap.name punto,s.name turno,x.absence_date fecha,x.scheduled_start_at inicio_programado,x.status estado FROM attendance_absences x JOIN users u ON u.id=x.guard_user_id JOIN clients c ON c.id=x.client_id JOIN locations l ON l.id=x.location_id JOIN access_points ap ON ap.id=x.access_point_id JOIN shifts s ON s.id=x.shift_id WHERE x.location_id IN ($m) AND x.scheduled_start_at BETWEEN ? AND ?$extra ORDER BY x.scheduled_start_at DESC LIMIT 5000",$base);
  if(in_array($type,['incidents','events'],true)){$incident=$type==='incidents'?" AND et.event_scope='incident'":'';$p=array_merge($ids,[$from,$to]);if($guard){$incident.=' AND e.guard_user_id=?';$p[]=$guard;}if($point){$incident.=' AND e.access_point_id=?';$p[]=$point;}return$this->all("SELECT e.id,e.title titulo,et.name tipo,e.priority prioridad,e.status estado,u.full_name vigilante,c.name cliente,l.name lugar,ap.name punto,e.description descripcion,e.occurred_at fecha,(SELECT COUNT(*) FROM event_evidence ee WHERE ee.event_id=e.id) evidencias FROM events e JOIN event_types et ON et.id=e.event_type_id LEFT JOIN users u ON u.id=e.guard_user_id JOIN clients c ON c.id=e.client_id JOIN locations l ON l.id=e.location_id LEFT JOIN access_points ap ON ap.id=e.access_point_id WHERE e.location_id IN ($m) AND e.occurred_at BETWEEN ? AND ?$incident ORDER BY e.occurred_at DESC LIMIT 5000",$p);}
  if($type==='rounds')return$this->all("SELECT r.id,u.full_name vigilante,c.name cliente,l.name lugar,ap.name punto,r.round_kind tipo,r.status estado,r.started_at inicio,r.ended_at fin,r.observations observaciones FROM rounds r JOIN users u ON u.id=r.guard_user_id JOIN clients c ON c.id=r.client_id JOIN locations l ON l.id=r.location_id JOIN access_points ap ON ap.id=r.access_point_id WHERE r.location_id IN ($m) AND r.started_at BETWEEN ? AND ?".($guard?' AND r.guard_user_id=?':'').($point?' AND r.access_point_id=?':'').' ORDER BY r.started_at DESC LIMIT 5000',array_merge($ids,[$from,$to],$guard?[$guard]:[],$point?[$point]:[]));
  if($type==='visits'){$p=array_merge($ids,[$from,$to]);$resident=$a['role_code']==='resident';if($resident)$p[]=$a['id'];return$this->all("SELECT vp.id,vp.visitor_name visitante,u.name unidad,l.name lugar,r.full_name residente,vp.host_name anfitrion,vp.reason motivo,vp.status estado,vp.scheduled_at programada,va.entry_at entrada,va.exit_at salida FROM visitor_passes vp JOIN units u ON u.id=vp.unit_id JOIN locations l ON l.id=vp.location_id JOIN users r ON r.id=vp.resident_user_id LEFT JOIN visitor_accesses va ON va.visitor_pass_id=vp.id WHERE vp.location_id IN ($m) AND vp.scheduled_at BETWEEN ? AND ?".($resident?' AND vp.resident_user_id=?':'').' ORDER BY vp.scheduled_at DESC LIMIT 5000',$p);}
  if($type==='supervisions')return$this->all("SELECT s.id,s.folio,c.name cliente,l.name lugar,u.full_name supervisor,s.status estado,s.started_at inicio,s.completed_at fin,s.observations FROM supervisions s JOIN clients c ON c.id=s.client_id JOIN locations l ON l.id=s.location_id JOIN users u ON u.id=s.supervisor_user_id WHERE s.location_id IN ($m) AND s.started_at BETWEEN ? AND ? ORDER BY s.started_at DESC LIMIT 5000",array_merge($ids,[$from,$to]));
  if($type==='guard_activity')return$this->all("SELECT sl.id,u.full_name usuario,sl.event_type accion,sl.ip_address ip,sl.user_agent dispositivo,sl.context_json contexto,sl.occurred_at fecha FROM security_logs sl JOIN users u ON u.id=sl.user_id WHERE u.surveillance_company_id=? AND sl.occurred_at BETWEEN ? AND ?".($guard?' AND sl.user_id=?':'').' ORDER BY sl.occurred_at DESC LIMIT 5000',array_merge([$a['surveillance_company_id'],$from,$to],$guard?[$guard]:[]));
  return$this->all("SELECT os.id,u.full_name vigilante,c.name cliente,l.name lugar,ap.name punto,os.status estado,os.started_at inicio,os.ended_at fin,os.entry_classification clasificacion FROM operational_sessions os JOIN users u ON u.id=os.guard_user_id JOIN clients c ON c.id=os.client_id JOIN locations l ON l.id=os.location_id JOIN access_points ap ON ap.id=os.access_point_id WHERE os.location_id IN ($m) AND os.started_at BETWEEN ? AND ? ORDER BY os.started_at DESC LIMIT 5000",array_merge($ids,[$from,$to]));}
 public function evidenceForEvents(array$ids):array{if(!$ids)return[];$m=implode(',',array_fill(0,count($ids),'?'));return$this->all("SELECT ee.id,ee.event_id,ee.media_type,ee.mime_type,ee.file_path,ee.captured_at FROM event_evidence ee WHERE ee.event_id IN ($m) ORDER BY ee.event_id,ee.captured_at",$ids);}
 private function filteredLocations(array$a,array$f):array{$locations=$this->locations($a);$client=(int)($f['client_id']??0);$location=(int)($f['location_id']??0);return array_values(array_map('intval',array_column(array_filter($locations,fn($l)=>(!$client||(int)$l['client_id']===$client)&&(!$location||(int)$l['id']===$location)),'id')));}
 private function locations(array$a):array{if($a['role_code']==='resident')return$this->all("SELECT DISTINCT l.id,l.client_id,l.name location_name,c.name client_name FROM resident_units ru JOIN units u ON u.id=ru.unit_id JOIN locations l ON l.id=u.location_id JOIN clients c ON c.id=l.client_id WHERE ru.resident_user_id=? AND ru.is_active=1",[$a['id']]);$sql="SELECT DISTINCT l.id,l.client_id,l.name location_name,c.name client_name FROM locations l JOIN clients c ON c.id=l.client_id";$p=[];if($a['role_code']==='supervisor'){$sql.=' JOIN user_location_scopes s ON s.location_id=l.id AND s.user_id=? AND s.is_active=1';$p[]=$a['id'];}elseif($a['role_code']==='admin'){$sql.=' LEFT JOIN user_location_scopes ls ON ls.location_id=l.id AND ls.user_id=? AND ls.is_active=1 LEFT JOIN user_client_scopes cs ON cs.client_id=c.id AND cs.user_id=? AND cs.is_active=1 WHERE c.surveillance_company_id=? AND (ls.user_id IS NOT NULL OR cs.user_id IS NOT NULL)';$p=[$a['id'],$a['id'],$a['surveillance_company_id']];}else{$sql.=' WHERE c.surveillance_company_id=?';$p[]=$a['surveillance_company_id'];}return$this->all($sql,$p);}
 private function one(string$q,array$p):?array{$s=$this->pdo->prepare($q);$s->execute($p);return$s->fetch()?:null;}private function all(string$q,array$p):array{$s=$this->pdo->prepare($q);$s->execute($p);return$s->fetchAll();}
}
