<?php
declare(strict_types=1);
namespace Vigilancia\Repositories;
use PDO;

final class SupervisionRepository
{
 public function __construct(private PDO$pdo){}
 public function locations(array$a):array{$sql="SELECT DISTINCT l.id,l.client_id,l.name location_name,c.name client_name FROM locations l JOIN clients c ON c.id=l.client_id";$p=[];if($a['role_code']==='supervisor'){$sql.=' JOIN user_location_scopes s ON s.location_id=l.id AND s.user_id=? AND s.is_active=1';$p[]=$a['id'];}elseif($a['role_code']==='admin'){$sql.=' LEFT JOIN user_location_scopes ls ON ls.location_id=l.id AND ls.user_id=? AND ls.is_active=1 LEFT JOIN user_client_scopes cs ON cs.client_id=c.id AND cs.user_id=? AND cs.is_active=1 WHERE (ls.user_id IS NOT NULL OR cs.user_id IS NOT NULL) AND c.surveillance_company_id=?';$p=[$a['id'],$a['id'],$a['surveillance_company_id']];return$this->all($sql.' ORDER BY c.name,l.name',$p);}else{$sql.=' WHERE c.surveillance_company_id=?';$p[]=$a['surveillance_company_id'];}return$this->all($sql.' ORDER BY c.name,l.name',$p);}
 public function points(array$ids):array{if(!$ids)return[];$m=implode(',',array_fill(0,count($ids),'?'));return$this->all("SELECT id,location_id,name FROM access_points WHERE is_active=1 AND location_id IN ($m) ORDER BY name",$ids);}
 public function schedules(array$a):array{$sql="SELECT ss.*,c.name client_name,l.name location_name,u.full_name creator_name,GROUP_CONCAT(ap.name ORDER BY ap.name SEPARATOR ', ') point_names FROM supervision_schedules ss JOIN clients c ON c.id=ss.client_id JOIN locations l ON l.id=ss.location_id JOIN users u ON u.id=ss.created_by JOIN supervision_schedule_points ssp ON ssp.schedule_id=ss.id JOIN access_points ap ON ap.id=ssp.access_point_id";$p=[];$where=[];if($a['role_code']==='supervisor'){$where[]='EXISTS(SELECT 1 FROM user_location_scopes us WHERE us.user_id=? AND us.location_id=ss.location_id AND us.is_active=1)';$p[]=$a['id'];}elseif($a['role_code']==='admin'){$where[]='c.surveillance_company_id=?';$p[]=$a['surveillance_company_id'];}if($where)$sql.=' WHERE '.implode(' AND ',$where);return$this->all($sql.' GROUP BY ss.id ORDER BY ss.scheduled_at DESC LIMIT 200',$p);}
 public function createSchedule(array$d,array$points):int{$s=$this->pdo->prepare("INSERT INTO supervision_schedules(client_id,location_id,frequency,scheduled_at,status,created_by,created_at,updated_at) VALUES(?,?,?,?, 'pending',?,UTC_TIMESTAMP(),UTC_TIMESTAMP())");$s->execute([$d['client_id'],$d['location_id'],$d['frequency'],$d['scheduled_at'],$d['user_id']]);$id=(int)$this->pdo->lastInsertId();$q=$this->pdo->prepare('INSERT INTO supervision_schedule_points(schedule_id,access_point_id) VALUES(?,?)');foreach($points as$p)$q->execute([$id,$p]);return$id;}
 public function schedule(int$id):?array{return$this->one('SELECT * FROM supervision_schedules WHERE id=?',[$id]);}
 public function schedulePoints(int$id):array{return array_map('intval',array_column($this->all('SELECT access_point_id FROM supervision_schedule_points WHERE schedule_id=?',[$id]),'access_point_id'));}
 public function create(array$d,array$points):int{$s=$this->pdo->prepare("INSERT INTO supervisions(folio,schedule_id,client_id,location_id,supervisor_user_id,status,started_at,created_at,updated_at) VALUES(?,?,?,?,?,'in_progress',UTC_TIMESTAMP(),UTC_TIMESTAMP(),UTC_TIMESTAMP())");$s->execute([$d['folio'],$d['schedule_id']?:null,$d['client_id'],$d['location_id'],$d['supervisor_id']]);$id=(int)$this->pdo->lastInsertId();$q=$this->pdo->prepare('INSERT INTO supervision_points(supervision_id,access_point_id) VALUES(?,?)');foreach($points as$p)$q->execute([$id,$p]);if($d['schedule_id'])$this->pdo->prepare("UPDATE supervision_schedules SET status='in_progress',updated_at=UTC_TIMESTAMP() WHERE id=? AND status='pending'")->execute([$d['schedule_id']]);return$id;}
 public function lists(array$a):array{$sql="SELECT s.id,s.folio,s.status,s.started_at,s.completed_at,s.observations,c.name client_name,l.name location_name,u.full_name supervisor_name,GROUP_CONCAT(ap.name ORDER BY ap.name SEPARATOR ', ') point_names,(SELECT COUNT(*) FROM supervision_evidence se WHERE se.supervision_id=s.id) evidence_count FROM supervisions s JOIN clients c ON c.id=s.client_id JOIN locations l ON l.id=s.location_id JOIN users u ON u.id=s.supervisor_user_id JOIN supervision_points sp ON sp.supervision_id=s.id JOIN access_points ap ON ap.id=sp.access_point_id";$p=[];$w=[];if($a['role_code']==='supervisor'){$w[]='EXISTS(SELECT 1 FROM user_location_scopes us WHERE us.user_id=? AND us.location_id=s.location_id AND us.is_active=1)';$p[]=$a['id'];}elseif($a['role_code']==='admin'){$w[]='c.surveillance_company_id=?';$p[]=$a['surveillance_company_id'];}if($w)$sql.=' WHERE '.implode(' AND ',$w);return$this->all($sql.' GROUP BY s.id ORDER BY s.started_at DESC LIMIT 200',$p);}
 public function supervision(int$id):?array{return$this->one("SELECT s.*,c.name client_name,l.name location_name,u.full_name supervisor_name,ru.full_name responsible_user_name FROM supervisions s JOIN clients c ON c.id=s.client_id JOIN locations l ON l.id=s.location_id JOIN users u ON u.id=s.supervisor_user_id LEFT JOIN users ru ON ru.id=s.responsible_user_id WHERE s.id=?",[$id]);}
 public function detail(int$id):array{$s=$this->supervision($id);if(!$s)return[];$s['points']=$this->all('SELECT ap.id,ap.name,ap.code FROM supervision_points sp JOIN access_points ap ON ap.id=sp.access_point_id WHERE sp.supervision_id=? ORDER BY ap.name',[$id]);$s['evidence']=$this->all('SELECT id,mime_type,file_size,watermark_text,captured_at FROM supervision_evidence WHERE supervision_id=? ORDER BY captured_at',[$id]);$s['comments']=$this->all('SELECT sc.comment,sc.created_at,u.full_name author_name FROM supervision_comments sc JOIN users u ON u.id=sc.author_user_id WHERE sc.supervision_id=? ORDER BY sc.created_at',[$id]);$s['present_guards']=$this->all("SELECT DISTINCT u.id,u.full_name,ap.name access_point_name FROM operational_sessions os JOIN users u ON u.id=os.guard_user_id JOIN access_points ap ON ap.id=os.access_point_id JOIN supervision_points sp ON sp.access_point_id=os.access_point_id AND sp.supervision_id=? WHERE os.status='active'",[$id]);$s['events']=$this->all("SELECT e.id,e.title,e.priority,e.occurred_at,u.full_name guard_name FROM events e LEFT JOIN users u ON u.id=e.guard_user_id WHERE e.location_id=? AND e.occurred_at>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 7 DAY) ORDER BY e.occurred_at DESC LIMIT 30",[$s['location_id']]);$s['rounds']=$this->all("SELECT r.id,r.status,r.started_at,r.ended_at,u.full_name guard_name FROM rounds r JOIN users u ON u.id=r.guard_user_id WHERE r.location_id=? AND r.started_at>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 7 DAY) ORDER BY r.started_at DESC LIMIT 30",[$s['location_id']]);return$s;}
 public function locationClient(int$l):?array{return$this->one('SELECT l.id,l.client_id,c.surveillance_company_id FROM locations l JOIN clients c ON c.id=l.client_id WHERE l.id=? AND l.is_active=1',[$l]);}
 public function validPoints(int$l,array$points):bool{if(!$points)return false;$m=implode(',',array_fill(0,count($points),'?'));return(int)$this->value("SELECT COUNT(*) FROM access_points WHERE location_id=? AND is_active=1 AND id IN ($m)",array_merge([$l],$points))===count(array_unique($points));}
 public function inScope(array$a,int$l):bool{if($a['role_code']==='superadmin')return true;if($a['role_code']==='admin')return(bool)$this->value('SELECT COUNT(*) FROM locations l JOIN clients c ON c.id=l.client_id WHERE l.id=? AND c.surveillance_company_id=?',[$l,$a['surveillance_company_id']]);return(bool)$this->value('SELECT COUNT(*) FROM user_location_scopes WHERE user_id=? AND location_id=? AND is_active=1',[$a['id'],$l]);}
 public function actorPin(int$id):?string{return$this->value('SELECT confirmation_pin_hash FROM users WHERE id=?',[$id])?:null;}
 public function updateActorPin(int$id,string$hash):void{$this->pdo->prepare('UPDATE users SET confirmation_pin_hash=?,updated_at=UTC_TIMESTAMP() WHERE id=?')->execute([$hash,$id]);}
 public function responsibleByName(int$l,string$name):?array{return$this->one("SELECT DISTINCT u.id,u.full_name,COALESCE(gp.pin_hash,u.confirmation_pin_hash) pin_hash FROM users u JOIN roles r ON r.id=u.role_id LEFT JOIN guard_profiles gp ON gp.user_id=u.id LEFT JOIN user_location_scopes ls ON ls.user_id=u.id AND ls.location_id=? AND ls.is_active=1 LEFT JOIN operational_sessions os ON os.guard_user_id=u.id AND os.location_id=? AND os.status='active' WHERE u.is_active=1 AND LOWER(u.full_name)=LOWER(?) AND (os.id IS NOT NULL OR ls.user_id IS NOT NULL) AND r.code IN ('guard','supervisor') LIMIT 1",[$l,$l,$name]);}
 public function addEvidence(array$d):int{$s=$this->pdo->prepare('INSERT INTO supervision_evidence(supervision_id,uploaded_by,mime_type,file_path,file_size,watermark_text,captured_at,created_at) VALUES(?,?,?,?,?,?,UTC_TIMESTAMP(),UTC_TIMESTAMP())');$s->execute([$d['supervision_id'],$d['user_id'],$d['mime'],$d['path'],$d['size'],$d['watermark']]);return(int)$this->pdo->lastInsertId();}
 public function evidence(int$id):?array{return$this->one('SELECT se.*,s.location_id FROM supervision_evidence se JOIN supervisions s ON s.id=se.supervision_id WHERE se.id=?',[$id]);}
 public function finish(int$id,array$d):void{$this->pdo->prepare("UPDATE supervisions SET status='completed',observations=?,completed_at=UTC_TIMESTAMP(),supervisor_confirmation_name=?,supervisor_confirmed_at=UTC_TIMESTAMP(),responsible_user_id=?,responsible_confirmation_name=?,responsible_confirmed_at=?,responsible_absent=?,absence_reason=?,updated_at=UTC_TIMESTAMP() WHERE id=? AND status='in_progress'")->execute([$d['observations'],$d['supervisor_name'],$d['responsible_id'],$d['responsible_name'],$d['responsible_id']?gmdate('Y-m-d H:i:s'):null,$d['absent'],$d['absence_reason'],$id]);$this->pdo->prepare("UPDATE supervision_schedules ss JOIN supervisions s ON s.schedule_id=ss.id SET ss.status='completed',ss.updated_at=UTC_TIMESTAMP() WHERE s.id=?")->execute([$id]);}
 public function comment(int$id,int$user,string$c):void{$this->pdo->prepare('INSERT INTO supervision_comments(supervision_id,author_user_id,comment,created_at) VALUES(?,?,?,UTC_TIMESTAMP())')->execute([$id,$user,$c]);}
 private function one(string$q,array$p):?array{$s=$this->pdo->prepare($q);$s->execute($p);return$s->fetch()?:null;}private function all(string$q,array$p):array{$s=$this->pdo->prepare($q);$s->execute($p);return$s->fetchAll();}private function value(string$q,array$p):mixed{$s=$this->pdo->prepare($q);$s->execute($p);return$s->fetchColumn();}
}
